### ISSUE TITLE
LowPower mode and RF TX Power

### ISSUE THREAD

**Issue by jperquin** [pvvx/ATC_MiThermometer#10]
What a brilliant evolution of atc1441's project! Very happy with the new developments.

I have about 20 of these installed at various off-site locations and want to find a balance between sufficient temp/hum/bat updates and battery life.

Also some locations have quite a few signal blockers between the sensor and the esp32 dev board (receiving the BLE signal), so want to make sure that we're getting at least a decent signal as well.

Any suggestions for fine-tuning?

**Comment by pvvx** [comment]
https://github.com/atc1441/ATC_MiThermometer/issues/134
