### ISSUE TITLE
no Bluetooth after update.

### ISSUE THREAD

**Issue by Squidsht** [pvvx/ATC_MiThermometer#100]
Hi
03mmc updated to 3.2r firmware.
With Xiaomi firmware device appears in phone when searching for Bluetooth devices. After installing your 3.2 firmware I can locate device via Telink flasher but it does not appear when searching on phone.
Ideas?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/119802544-4d632c80-bee7-11eb-8d38-b9728889c1a4.png)
Turning on results in additional power consumption from the battery.

**Comment by pvvx** [comment]
@Squidsht  Describe for what purpose you need a device in the BT system list, if standard tools do not have the ability to work with BLE devices?
