### ISSUE TITLE
Multiple bluetooth adapters

### ISSUE THREAD

**Issue by stefanheijnen** [pvvx/ATC_MiThermometer#103]
Hi,

I've played around with your flasher for a while. I always succeeded to flash an custom firmware, but I never got the the part where the config would be displayed on the screen.

Ultimately I found the issue. I have 2 bt adapters in my pc. 1 onboard and 1 usb. The onboard has such a bad range since it is in a metal casing. That's why I added an usb adapter in my usb hub on my desktop.

I had the onboard bt adapter disabled in my bios. For some reason it got enabled again. Even though in my OS (Manjaro Linux) I had that one disabled and selected the usb as default, chrome always wanted to use the onboard adapter. 

So I think this is a issue with Chrome and not your script, but would it be possible to select an adapter to use?

Anyway, hopefully I can save other users with multiple adapters some time when they try to figure out why it is not working.

**Comment by yousaf465** [comment]
Try flashing using a mobile (Android). I flashed mine using a Samsung Note 10.
