### ISSUE TITLE
Configuration Screen only shown for very short time

### ISSUE THREAD

**Issue by Huebenthal** [pvvx/ATC_MiThermometer#104]
I flashed it successfully and try to change the configuration. After connection to the device in the Telink Flasher the configuration screen appears but disappears after 2-3s again and the device is disconnected. Setting any configuration is not possible in this short time.
Chrome browser in Android 11

**Comment by rocket59** [comment]
Have the same issue (3.2 firmware) on an old phone (running android 6.01). The device disconnects within a minute of connection and it also takes a few tries to connect/reconnect.

**Comment by chris4git** [comment]
I have the same problem : fresh flash of 3.2 from original firmware -> connect -> the form is displayed -> 10s-15s later, auto-disconnect.
A connection on a previously upgraded from 2.x to 3.2 is stable.
Chrome on Android 10

**Comment by chris4git** [comment]
Update : I removed and replaced the battery and could change the configuration. So probably a bad contact...

**Comment by tablatronix** [comment]
Same, had to reboot it to get it to work again. Odd.

**Comment by kdre** [comment]
I have the same problem. A reboot (pulling and reinserting the battery) did not help.
Chrome on Linux: No config options visible at all.
Chrome on Android: Config option visible for short time and then they disappear.

**Comment by MiguelCosta** [comment]
I also have issues after update to firmware 3.2

When I try to connect, the device disconnects after a few seconds 😢 

Chrome on Windows, Edge on Windows and Chrome on Android have the same issue.

![image](https://user-images.githubusercontent.com/645482/132775184-31981a0e-21e1-460d-988d-31cb29733515.png)
