### ISSUE TITLE
CGG1 M Version: "Do Activation" not working

### ISSUE THREAD

**Issue by nr001** [pvvx/ATC_MiThermometer#107]
Hello,
i can successfully connect to my Qingping Cleargrass M-Version sensor. However when i click on "Do Activation" nothing happens anymore. The Chrome Console only says that a certain command was sent, no error message or anything like this.
I already tried doing the activation with different browser & devices => everywhere the same.
Any ideas?
thx a lot :)

**Comment by yerkanian** [comment]
Long-press the back button before connecting to CGG1.

**Comment by nr001** [comment]
> 
> 
> Long-press the back button before connecting to CGG1.

Thx a lot, this worked :)
