### ISSUE TITLE
Complete deactivation of smiley on MHO-C401 not possible

### ISSUE THREAD

**Issue by Flugente-19** [pvvx/ATC_MiThermometer#109]
Today I flashed the FW v3.1 on two devices LYWSD03MMC and MHO-C401. There is a small issue with the MHO-C401: It is not possible to completely deactivate the smiley. When I select the blank smiley, the two brackets are still visible. Could you please check it?

![MHO-C401_LYWSD03MMC](https://user-images.githubusercontent.com/81471370/123810180-7fa2e800-d8f2-11eb-9d68-a85fd6d3972b.png)

**Comment by MacSass** [comment]
Hi,
yes - that is because how the brackets are linked to the . by hardware - thus they are not individually adressable per my understaning. See closed issue and explanation here: [https://github.com/pvvx/ATC_MiThermometer/issues/63](url)

**Comment by Flugente-19** [comment]
Okay. Thank you for the fast response.
