### ISSUE TITLE
No notifications in Connection mode

### ISSUE THREAD

**Issue by miksumin** [pvvx/ATC_MiThermometer#115]
I am using LYWSD03MMC sensor with custom FW ver.3.2 in connection mode. Connection and registering Service UUID 0x1F10 with Characteristic UUID 0x1F1F for notify successful. But no any notifications received. What may be a problem?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer#bluetooth-connection-mode
![image](https://user-images.githubusercontent.com/12629515/129112350-03fdbd46-be46-4b7e-ba30-7304c7510ad4.png)
https://github.com/pvvx/ATC_MiThermometer#primary-service-uuid-0x1f10-characteristic-uuid-0x1f1f
![image](https://user-images.githubusercontent.com/12629515/129112410-488e961e-7098-4d8e-a96b-78446ad957cc.png)
Sample:  https://pvvx.github.io/ATC_MiThermometer/GraphAtc2.html

Test On/Off notify: https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
![image](https://user-images.githubusercontent.com/12629515/129112628-4a54e577-792d-417f-8f36-cd5c99b20391.png)
