### ISSUE TITLE
Can we disable logging to internal storage?

### ISSUE THREAD

**Issue by tetsuo55** [pvvx/ATC_MiThermometer#116]
And if so how?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/130336487-783024e9-cf1a-4dff-8938-84381ff10088.png)
https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

**Comment by tetsuo55** [comment]
Thanks, there aren't any tooltips on Android so i never saw that.
