### ISSUE TITLE
Humidity (LYWSD03MMC)

### ISSUE THREAD

**Issue by ACrazyConcept** [pvvx/ATC_MiThermometer#117]
Hi

Finally got my LYWSD03MMC flashed. Totally cool improvement.

I was just wondering if the humidity sensor is also able to provide the same precision and update frequency as the temperature?

![image](https://user-images.githubusercontent.com/36438756/130412880-37fe2768-c089-486f-afe6-cfa6ce7faec8.png)

**Comment by tetsuo55** [comment]
Mine are as detailed with humidity as they are with temperature, strange that yours stays like that

**Comment by giannoug** [comment]
Same here, values seem to have the same precision:
![image](https://user-images.githubusercontent.com/509474/130662131-4560ed3d-2767-48b8-9e04-af99234f08e0.png)

Have you noticed that humidity might need offset setting? Not sure if the default configuration reports the correct values.

Can anyone confirm?

**Comment by ACrazyConcept** [comment]
I just added the sensor on a new HA and there I get the same level of detail in both humidity and temperature. Still strange though. But it's resolved.
