### ISSUE TITLE
Can't connect after updating firmware to 3.2

### ISSUE THREAD

**Issue by acronce** [pvvx/ATC_MiThermometer#118]
I flashed an LYWSD03MMC to v3.2 and after it succeeded I could not reconnect to the device. It doesn't even show up as a bluetooth device any more in the Windows -> Settings -> Bluetooth.

The device itself seems happy. It's displaying the temp and humidity like before. 

I power cycled it by removing the battery and putting it back in. It still displays the temp, but now longer appears as a Bluetooth device.

Any suggestions?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/100

**Comment by acronce** [comment]
That seems to be a different problem. In my case after flashing I cannot see the device in the Telink Flasher. It basically disappeared after flashing and will not reconnect.

**Comment by jddonovan** [comment]
I have zero issues with my Windows computer with a relatively new bluetooth adapter, supporting BT5.0. I also have an atomic pi with BT 4.0 using bluetooth2mqtt and I couldn't get any sense on why it wouldn't connect or read the mi-thermometer whereas e.g. my smart band was detected ok.

Someone in the review section mentioned that they could not get this to work on BT 4.0 adapter, but using a BT 4.2 it worked fine. Could this be the reason? The sensor requiring version 4.2 minimum for successful broadcast after flashing?

**Comment by MiguelCosta** [comment]
I also have issues after update to firmware 3.2

In my case, after flashing I can't configure the settings. When I try to connect, the device disconnects after a few seconds 😢 

![image](https://user-images.githubusercontent.com/645482/132775184-31981a0e-21e1-460d-988d-31cb29733515.png)

**Comment by acronce** [comment]
I moved to a different computer (a Mac running Chrome) and was able to connect to the thermometer. This allowed me to configure the device with no further issues.
