### ISSUE TITLE
Pincode length check

### ISSUE THREAD

**Issue by sebitnt** [pvvx/ATC_MiThermometer#119]
First of all: Thank you so much for this great project!!!

I had a little headache after setting the pincode on a LYWSD03MMC. I entered a pincode of 8 digits and got the message, that it should only be 6 digits long. Therefore I entered a 6 digit code and clicked the set button again. After disconnecting I tried to reconnect with the 6 digit code, which failed every time. After some trying an head scratching I just entered the 8 digit code on my Android device and the connection was fine. So I think what happened was that the 8 digit code was set fine, even when I got the error message. Therefore there should be some kind of check for the pincode length or even better: allowing longer codes if possible.

Thank you again!

**Comment by pvvx** [comment]
In the SDK description and examples from Telink, 6 characters are recommended ...
