### ISSUE TITLE
Storage capacity

### ISSUE THREAD

**Issue by vanMacG** [pvvx/ATC_MiThermometer#120]
Hi, I have a rather basic question, but I didn't find an answer on this...
I want to use the sensor as a simple logging device for temp and humidity. Actually I don't have a smart home system or "central device" or anything.
How many data points can be stored in the device before the storage runs out of memory aka what would be the interval I have to read out the data and save it away? If the interval is big enough I wouldn't care running around and do the backup "manually".

**Comment by pvvx** [comment]
Memory for storage: Ring buffer from 19632 records of average measurements of three values from sensors (temperature, humidity, battery voltage) and recording time.
The recording step is set in measurement intervals:

![image](https://user-images.githubusercontent.com/12629515/132932113-5461e798-251f-4fe3-b1d8-354e85bf3645.png)

The default setting for LYWSD03MMC is 2.5 sec * 4 * 60 = 600 sec.

19632 * 600 sec ~ 136 day.

![image](https://user-images.githubusercontent.com/12629515/132932310-4c6de5f7-003f-44b6-9981-3161828750d1.png)
