### ISSUE TITLE
no more display on LYWSD03MMC after flash

### ISSUE THREAD

**Issue by fschaer** [pvvx/ATC_MiThermometer#134]
Hi,

I used the webflasher to flash a brand new LYWSD03MMC. So I flashed version 3.2 pf the firmware.
It appeared to work... but none of the settings I set for the display were working. And I started getting disconnects, then no more connection.

Changing the bluetooth name actually worked.

I pulled of the battery, then put it back : got no more display, and no connection

I then decided to open the device (this is hardware revision 1.6 apparently), and successfully flashed version 3.1 of the firmware using ttyUSB. This is when I found that while connected to the ttyUSB device, I still don't have any display (how is this working by the way ? no wire between pcb and display, just a black thingy bar... ?)

=> measured the CR2032 : it's completely dead... so it died in about 10 minutes. I'll try tonight with another battery, but I have the impression the sensor is frying the batteries.

Anyway : would you have an idea how I can get a display back ?
I also don't seem to get any data values : when I click on the web flasher on "get the last 50 records", this gives me : 

```
20:23:16: Hardware Version: LYWSD03MMC, Software Version: 3.1
20:23:16: Custom config: [45, 1, 0, 0, 40, 4, 169, 124, 49, 56, 60]
20:28:36: Send cmd GetMemo ok
20:28:36: Memo end: 0
```

Any help would be appreciated (I got 2 other devices which I'm a bit affraid to flash the same way...)

**Comment by atc1441** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/125
