### ISSUE TITLE
New advertisement format?

### ISSUE THREAD

**Issue by alekc** [pvvx/ATC_MiThermometer#135]
I am extremely confused by the new (?) advertisement format. 

I've recently flashed my sensors with 3.2 version, and my old scripts related to the temperature read were not functioning anymore. 

Having a look inside, I found that when I set for custom advertisement (without any flags), I am getting following beacon:
`12 16 1A 18 57 74 CE 38 C1 A4 B2 07 7D 1A 37 0A 2E 18 0F 0B 09 4C 69 76 69 6E 67 52 6F 6F 6D`

Standing by the documentation, we should have 
```
uint8_t     size;   // = 19
uint8_t     uid;    // = 0x16, 16-bit UUID
uint16_t    UUID;   // = 0x181A, GATT Service 0x181A Environmental Sensing
uint8_t     MAC[6]; // [0] - lo, .. [6] - hi digits
int16_t     temperature;    // x 0.01 degree
uint16_t    humidity;       // x 0.01 %
uint16_t    battery_mv;     // mV
uint8_t     battery_level;  // 0..100 %
uint8_t     counter;        // measurement count
uint8_t     flags;  // GPIO_TRG pin (marking "reset" on circuit board) flags: 
                    // bit0: Reed Switch, input
                    // bit1: GPIO_TRG pin output value (pull Up/Down)
                    // bit2: Output GPIO_TRG pin is controlled according to the set parameters
                    // bit3: Temperature trigger event
                    // bit4: Humidity trigger event
```

Unless I am reading my format wrong (it has been a while after all), it roughly decodes as 
size: 12
uid: 16
UUID: 181A
MAC: inverted 57 74 CE 38 C1 A4
temperature: 07B2 
humidity: 1A7D
battery_mv: 0A37
battery_lvl: 2e
counter: 18 
flags: 0F 0B 09 4C 69 76 69 6E 67 52 6F 6F 6D

After the Mac entry, we have a length of 21 bytes and not 12. Also, 12 is not 19?

Any clarification would be appreciated.

**Comment by joesensoric** [comment]
How do you read the beacon data? The flags are included in one byte, "0F" in your dump. The bytes starting at "4C" are ASCII-charcters reading "LivingRoom". Somehow this text has been added to your received data.

**Comment by swiergot** [comment]
@pvvx Not to create a new issue, may I ask here why the size reported is 18 (0x12) while the doc says 19?
