### ISSUE TITLE
LYWSD03MMC - after flash all segments are visible

### ISSUE THREAD

**Issue by DastyDiesel** [pvvx/ATC_MiThermometer#136]
Hello,
I did flash of my LYWSD03MMC using website. After it the display was freezed. I removed battery for a couple of minutes and after starting the display lights completely (it means each segment is visible). I can still connect to device via website for flashing but I need also values on display. Do you have any idea what is wrong?
Thank you.

**Comment by ChefkeGremmen** [comment]
I have the exact sane issue, already 'bricked' 2 devices.

**Comment by ChefkeGremmen** [comment]
@DastyDiesel  ; have a look at this comment https://github.com/pvvx/ATC_MiThermometer/issues/125#issuecomment-937552241
I tried flashing the mentioned firmware back to my device with the webupdater and I got mine working again.
It seems they are in the middel of analysing the hardware changes. @pvvx ; please put a big banner in the readme to only flash these firmware below a certain HW version.

**Comment by vladtsit** [comment]
> @DastyDiesel ; have a look at this comment [#125 (comment)](https://github.com/pvvx/ATC_MiThermometer/issues/125#issuecomment-937552241)
> I tried flashing the mentioned firmware back to my device with the webupdater and I got mine working again.
> It seems they are in the middle of analyzing the hardware changes. @pvvx ; please put a big banner in the readme to only flash these firmware below a certain HW version.

Have the same issue, which firmware you mean to get the device recovered?

**Comment by pvvx** [comment]
New hardware versions Xiaomi LYWSD03MMC B1.6 and B1.9 are compatible with custom firmware ver 3.3
