### ISSUE TITLE
C401 fw - error correction

### ISSUE THREAD

**Issue by michapr** [pvvx/ATC_MiThermometer#14]
Hi,

I'm testing the latest version (12) for 401 - it is working great, thanks!
Energy usage is minimal, so now the device can be used as expected ;)

Only one thing - I have got within the last 24hours 3 wrong results of temp/hum (>200 each).
Had it never before with atc or your older fw.
Possible any wakeup issue?

Maybe you can add a simple check before sending? temp <100 and hum<100 ?
I think it is a simple way...

Thanks again!

Michael

PS: I would recommend to set the comfort smiley as default in the bin ;)

**Comment by pvvx** [comment]
> Only one thing - I have got within the last 24hours 3 wrong results of temp/hum (>200 each).

? Temperature sensor CRC check enabled.

**Comment by michapr** [comment]
Yes,, I'm not about CRC error.
I think the sensor itself give back a wrong value after wakeup.
