### ISSUE TITLE
Stop looping display

### ISSUE THREAD

**Issue by Bubbleman75** [pvvx/ATC_MiThermometer#142]
Hello

I there a way stopping the "3 LCD Display Screens (Looping): Temperature & Humidity & Comfort, Temperature & Battery Level, Clock" feature?
I only want temperature & Humidity on screen (but full advertising)

Thanks
Thomas

**Comment by pvvx** [comment]
Using the TelinkMiFlasher.html you have various configuration options.
![image](https://user-images.githubusercontent.com/12629515/139740766-3aea38a8-5560-4a61-abe0-0194c95e2c91.png)
