### ISSUE TITLE
Settings screen not visible after flashing

### ISSUE THREAD

**Issue by dashavoo** [pvvx/ATC_MiThermometer#143]
Flashed from https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html but on connect there is no settings screen.

Detected alternative Firmware?

![pvvx github io_ATC_MiThermometer_TelinkMiFlasher html](https://user-images.githubusercontent.com/3750013/140833726-89f83b4d-40d2-4357-a0d2-116b447d49ec.png)

**Comment by Protoncek** [comment]
I guess that you (by mistake?) flashed ATC's firmware instead of "pvvx" one. Go to that page and re-flash there.

**Comment by dashavoo** [comment]
It worked (the same device and firmware without reflashing) when I tried in Chrome on Windows instead of Linux. Sorry for the noise.
