### ISSUE TITLE
B1.9 Advertising Problem

### ISSUE THREAD

**Issue by xfactory9025** [pvvx/ATC_MiThermometer#155]
My device hardware B1.9. I installed ATC_V34d. The image is as seen in the picture. Temperature and humidity information shows as no value on the phone.
![IMG_6616](https://user-images.githubusercontent.com/83598671/144035061-30cd882a-d95e-435b-bf9a-5d50d3108b77.JPG)

**Comment by pvvx** [comment]
https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
Log: Hardware Version: LYWSD03MMC B1.9, Software Version: 3.4, Sensor: SHT4x ?

**Comment by xfactory9025** [comment]
> https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html Log: Hardware Version: LYWSD03MMC B1.9, Software Version: 3.4, Sensor: SHT4x ?

Yes

**Comment by pvvx** [comment]
The reasons for this behavior have not been established. More suitable option - LCD from version 1.4, LCD driver from 1.9?
Could you clarify the production date on the box?

**Comment by xfactory9025** [comment]
![IMG_6617](https://user-images.githubusercontent.com/83598671/144176509-7842395b-763d-4606-89c1-06531d1d27b9.JPG)

**Comment by Protoncek** [comment]
I just received two of those (2021.08) and they have B1.9 (i checked by opening them). Flashed both of them with pvvx succesfully.

**Comment by xfactory9025** [comment]
> Az iki önce tane (2021.08) aldım ve B1.9'a sahipler (açarak kontrol ettim). Her ikisi de etkili bir şekilde pvx ile flashladım.

I did not understand why this happened.

**Comment by pvvx** [comment]
Xiaomi LYWSD03MMC Original Firmware v1.0.0_0130 working fine?

**Comment by xfactory9025** [comment]
> Xiaomi LYWSD03MMC Original Firmware v1.0.0_0130 working fine?

yes

**Comment by pvvx** [comment]
What version of HW does the original firmware show?

**Comment by xfactory9025** [comment]
B1.9

**Comment by xfactory9025** [comment]
I have installed atc1441 version. The values ​​do not appear in the advertisement broadcast on the phone, but when used with the esp32 code here, the values ​​appear on the serial monitor. Working with Esp32 solved my problem.
