### ISSUE TITLE
Maximum number of BLE devices?

### ISSUE THREAD

**Issue by Protoncek** [pvvx/ATC_MiThermometer#156]
Recently i connected some new xiaomi’s, so currently i have totally 8 of them. I start to wonder, is it any limit in number of BLE devices so that they won’t disturb each other? 
Should i change advertising interval on each for just a little, so if two of them “decide” to send it’s data simultaneously they will sooner or later go “out of sync”…? I don’t know BT protocol, so i don’t know how these devices deal with colisions.

I have them connected to two esp32 (esphome) modules, 4 of them work ok for now on each module. Will be ok if i add even more of them to a single esp32?

**Comment by pvvx** [comment]
A common sniffer on one channel receives BLE ads from hundreds of devices per second. The bit rate is 1 Mbps. Those. up to 100 kilobytes per second.
The device uses transmission duplication. With default settings, the thermometer provides duplicate readings 4 times in 3 gears on 3 channels.

**Comment by Protoncek** [comment]
Aha… many thanks for detailed explanation. So, in short: it should work without any problem…
I used to have over 10 wifi modules (espxx), now i replaced many of them with xiaomi’s (basically most of those which only measure temp and humidity). Main advantage of xiaomi’s is battery power, so if they will work ok i’ll buy some more of them, so it’s good to know that they will work ok.
Thanks again!

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/147330222-c14504b7-547f-4cb3-bbad-c2993c13fd18.png)

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/157172224-962ae53a-4913-4c40-8fad-4f94f5db15fc.png)
There are no gaps in the graphs in HA...
All automation scripts work flawlessly.

**Comment by Protoncek** [comment]
Nice! Thanks for info! I bet you already wrote, but i can't remember: which BT receiver system (hardware, FW) do you use?

**Comment by pvvx** [comment]
The cheapest USB-BT. Ver Bluetooth 4.0 :) 
```
lsusb -v -s 006:002

Bus 006 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          224 Wireless
  bDeviceSubClass         1 Radio Frequency
  bDeviceProtocol         1 Bluetooth
  bMaxPacketSize0        64
  idVendor           0x0a12 Cambridge Silicon Radio, Ltd
  idProduct          0x0001 Bluetooth Dongle (HCI mode)
  bcdDevice           88.91
  iManufacturer           0
  iProduct                2 CSR8510 A10
....
```

**Comment by Protoncek** [comment]
Aha...thanks. Since my synology  (where my HA is) is located at one corner of my house using BT dongle wouldn't reach to all my Xiaomi's, that''s why i use ESP32. But, as said a few times already, Tasmota works pretty well, way better than ESPHome.

**Comment by pvvx** [comment]
This is in a separate house-workshop for a hobby, 6x6 meters, all internal partitions are wooden...
