### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by Le-Ze** [pvvx/ATC_MiThermometer#159]
Hi.
When I upload your firmware, how cleans over ESP 32?

**Comment by atc1441** [comment]
Please do not open 2 issues on both repos.

https://github.com/atc1441/ATC_MiThermometer/issues/234

**Comment by Le-Ze** [comment]
I'm very sorry.
It works. I'm very satisfied, thank you for the project. You're great.
Which to buy?
You write Qingping Temp & RH Monitor (CGG1-Mijia)

https://www.aliexpress.com/item/1005002030407606.html
Is there written Product Model: CGDK2
Will Flas firmware go?
Thank you
