### ISSUE TITLE
Qingping Temp & RH Monitor (CGG1-Mijia)

### ISSUE THREAD

**Issue by Le-Ze** [pvvx/ATC_MiThermometer#161]
Which to buy?
You write Qingping Temp & RH Monitor (CGG1-Mijia)

https://www.aliexpress.com/item/1005002030407606.html
Product Model: CGDK2
Will your firmware work?
Will I do Flash?
Thank you

**Comment by pvvx** [comment]
CGDK2 is not supported.

**Comment by Le-Ze** [comment]
Will it ever support?
Do you work on firmware?

**Comment by pvvx** [comment]
I do not have CGDK2 and is not expected.
