### ISSUE TITLE
Smiley settings manual...?

### ISSUE THREAD

**Issue by Protoncek** [pvvx/ATC_MiThermometer#162]
I wonder, if there any manual written anywhere for smiley settings? I'm kinda lost in all those settings... i mean  second and fourth line in miflasher config.  Any information/explanation would be nice.  
In second line there's "123.4" and "99%" by default. what those numbers mean?
In fourth line i know what "battery" and "clock" means, but that's pretty much all.

Thanks!

**Comment by pvvx** [comment]
> In second line there's "123.4" and "99%" by default. what those numbers mean? 

This is a test case for displaying third-party data. For those who want to use the readings on the indicator from third-party software.

**Comment by Protoncek** [comment]
Aaa... ok, many thanks. That explains why suddenly i've got some strange  zeroes on my LCD alternating with correct temp and humidity data.
The reason why i went tinkering this is that my smiley is "sleeping" (not "happy") while room temp is just over 20 and humidity somewhat below 50%, so i'd like to change that. I guess that it's possible (i mean WHEN smiley changes) ?  I know, it's just cosmetic... but still... if it's there, why not?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/145374715-59a850d9-d6eb-4fab-be8c-accf9b20f36c.png)
![image](https://user-images.githubusercontent.com/12629515/145374828-27399b38-7fc2-40f3-b36a-07bf2d40509a.png)
