### ISSUE TITLE
Build custom image for MHO-C401

### ISSUE THREAD

**Issue by vekonyat** [pvvx/ATC_MiThermometer#168]
Hi, if I build a new image using the standard source code, will it work on MHO-C401 too, or is some board specific setting needed, or is it automatic?

**Comment by pvvx** [comment]
#define DEVICE_TYPE	DEVICE_MHO_C401

https://github.com/pvvx/ATC_MiThermometer/blob/master/src/app_config.h#L14

**Comment by vekonyat** [comment]
Ah, Thank you!
