### ISSUE TITLE
Reversed MAC address for CGG1

### ISSUE THREAD

**Issue by mvdklip** [pvvx/ATC_MiThermometer#169]
I just flashed a CGG1 with custom firmware 3.5. Works fine. However I did notice that it reads out the device MAC address in reverse. It's both advertising from this reversed MAC address as well as giving it a name (CGG_******) which uses the first three digits of the MAC address in reverse.

The original MAC address starts with 58:2D, the flashed MAC address ends in 2D:58.

**Comment by pvvx** [comment]
Qingping CGG1-M changed the standard SDK procedure for getting MAC address from Flash.
Corrected in the new version CGG1_v35b.bin.

**Comment by mvdklip** [comment]
Confirmed. Thanks!
