### ISSUE TITLE
Clock is off by about a minute per day.

### ISSUE THREAD

**Issue by lukcz** [pvvx/ATC_MiThermometer#170]
I am using version 3.4 of firmware and noticed that after couple of days the clock displayed on thermometer is off by a few minutes. My HW version is LYWSD03MMC B1.9.

**Comment by pvvx** [comment]
[Clock information not reliable](https://github.com/pvvx/ATC_MiThermometer/issues/56) or is not displayed on the LCD?

**Comment by lukcz** [comment]
Yep, that is a duplicate - same as #56.
