### ISSUE TITLE
Where to set LCD refresh rate?

### ISSUE THREAD

**Issue by vekonyat** [pvvx/ATC_MiThermometer#171]
Hi Victor, I'm using Lywsd003mmc as a timer, and try to show seconds on the LCD. Maybe could you please help me, where can I change the 5sec LCD refresh rate to 1 sec in the src or in SDK? I just can't figure out.
Many thanks!

**Comment by pvvx** [comment]
To save energy, the program is focused on waking up on RF transmit and receive events.
There is no separate timer for updating the LCD.

**Comment by vekonyat** [comment]
Thank you it's clear now.
