### ISSUE TITLE
MAC address

### ISSUE THREAD

**Issue by liuluping0106** [pvvx/ATC_MiThermometer#178]
Hi, i use the new Custom firmware on LYWSD03MMC. How can i get the mac address now?

**Comment by mmkrysiak** [comment]
I use BLE Scanner App on smartphone :)

**Comment by pvvx** [comment]
Connect  [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) &
![image](https://user-images.githubusercontent.com/12629515/149703261-694f0e39-bc47-4338-9b33-6960635bbe39.png)
