### ISSUE TITLE
Qingping Temp & RH M batery level

### ISSUE THREAD

**Issue by mmkrysiak** [pvvx/ATC_MiThermometer#180]
There is big difference between neighbour reports of battery level.
Is it any chance to fix it?
Please take a look at the report below

[20:32:45][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:32:45][D][pvvx_mithermometer:121]:   Temperature: 19.92 °C
[20:32:45][D][pvvx_mithermometer:124]:   Humidity: 39.03 %
[20:32:45][D][pvvx_mithermometer:127]:   **Battery Level: 82 %**
[20:32:45][D][pvvx_mithermometer:130]:   Battery Voltage: 2.946 V

[20:32:57][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:32:57][D][pvvx_mithermometer:121]:   Temperature: 19.89 °C
[20:32:57][D][pvvx_mithermometer:124]:   Humidity: 39.04 %
[20:32:57][D][pvvx_mithermometer:127]:   **Battery Level: 75 %**
[20:32:57][D][pvvx_mithermometer:130]:   Battery Voltage: 2.879 V

[20:33:02][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:33:02][D][pvvx_mithermometer:121]:   Temperature: 19.89 °C
[20:33:02][D][pvvx_mithermometer:124]:   Humidity: 39.04 %
[20:33:02][D][pvvx_mithermometer:127]:   **Battery Level: 75 %**
[20:33:02][D][pvvx_mithermometer:130]:   Battery Voltage: 2.879 V

[20:33:17][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:33:17][D][pvvx_mithermometer:121]:   Temperature: 19.90 °C
[20:33:17][D][pvvx_mithermometer:124]:   Humidity: 39.05 %
[20:33:17][D][pvvx_mithermometer:127]:   **Battery Level: 83 %**
[20:33:17][D][pvvx_mithermometer:130]:   Battery Voltage: 2.947 V

[20:33:22][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:33:22][D][pvvx_mithermometer:121]:   Temperature: 19.90 °C
[20:33:22][D][pvvx_mithermometer:124]:   Humidity: 39.05 %
[20:33:22][D][pvvx_mithermometer:127]:   Battery Level: 83 %
[20:33:22][D][pvvx_mithermometer:130]:   Battery Voltage: 2.947 V

[20:33:38][D][pvvx_mithermometer:118]: Got PVVX MiThermometer (5A:58:2D:34:11:88):
[20:33:38][D][pvvx_mithermometer:121]:   Temperature: 19.93 °C
[20:33:38][D][pvvx_mithermometer:124]:   Humidity: 39.05 %
[20:33:38][D][pvvx_mithermometer:127]:   Battery Level: 75 %
[20:33:38][D][pvvx_mithermometer:130]:   Battery Voltage: 2.879 V

**Comment by pvvx** [comment]
Clean the battery and contacts.

**Comment by mmkrysiak** [comment]
I don't think this is a problem. Sensors are brand new, batteries to.  I've found out the issue after firmware flash. Sensors with original firmware  don't report battery status at all. Hardware issue?

**Comment by pvvx** [comment]
I don't understand your problem. 
The battery voltage is different and depends on the load. The load at work is different and the voltage is different. In advertising mode, there is active and passive scanning - with active, there is an additional transmission and more consumption. The battery voltage is lower for a while after this event.

**Comment by pvvx** [comment]
It is possible to oxidize the GPIO_PB5 pin on the SoC TLSR8253F512ET32 (CGG1)?
In v3.5c, battery voltage measurement is done using GPIO_PB0, which does not come out of the chip package.

**Comment by mmkrysiak** [comment]
I'll try to explain. I 've just flashed several brand new xiomi temp sensors and noticed that battery voltage and level for CGG1s (and only for those models) are very unstable. Please take a look at charts below (pure reports without any filtering)

First for the  LYWSD03MMC wchich looks OK for the reference:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/71908475/150221331-aefaf974-8838-4b18-8879-43ca05ab91b8.png">
<img width="326" alt="image" src="https://user-images.githubusercontent.com/71908475/150221500-80bd146a-8087-4919-bb97-610528b12051.png">

and for the  CGG1 (Qingping Temp & RH M) - same time and enviroment
<img width="322" alt="image" src="https://user-images.githubusercontent.com/71908475/150221880-9deec0d2-7669-491e-aec6-c8b63d6c9f3f.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/71908475/150221930-6f47e89e-8e22-4093-8843-a107b8f5227a.png">

For both sensors within shorter period of time
<img width="316" alt="image" src="https://user-images.githubusercontent.com/71908475/150222131-668d015f-61cb-4360-a242-0a30ba3771e4.png">
<img width="319" alt="image" src="https://user-images.githubusercontent.com/71908475/150222219-b45e55fc-cf57-4966-9715-1870a8e720b6.png">

As you can see difference between neighbours reports for CGG1 are to big and changes to fast to be true. I don't think it could be explained by the load, temperature etc.

**Comment by pvvx** [comment]
CGG1 one of all has internal capacitors for power supply and additional switches for power input from the battery. This may have an effect.
Is this observed on the new v3.5c?

> In v3.5c, battery voltage measurement is done using GPIO_PB0, which does not come out of the chip package.

In the previous version, the voltage power value was digitized from the GPIO going to additional elements...

**Comment by mmkrysiak** [comment]
it looks the same on the new v3.5c :(
<img width="322" alt="image" src="https://user-images.githubusercontent.com/71908475/150387443-6980f145-ec65-461c-8793-7e387783ca25.png">

**Comment by Protoncek** [comment]
That's only under 0.1V difference, which is  actually quite excellent for this device. ADC in ESP32 isn't "state of the art", you know. Good, stable ADC's are pretty expensive. ADC inside ESP32 is definitely only of average quality. It relies on internal voltage refefence, which can fluctuate with chip consumption and so you get varying ADC result.

**Comment by mmkrysiak** [comment]
0.1V accuraccy on 3V battery it's not an excellent result. It's makes 10% difference on battery level! 
Note that much cheaper LYWSD03MMC is 10x more precise.
<img width="322" alt="image" src="https://user-images.githubusercontent.com/71908475/150406607-52485ffa-2f2f-41ba-8045-0667b1a695a4.png">

**Comment by pvvx** [comment]
> it looks the same on the new v3.5c :( <img alt="image" width="322" src="https://user-images.githubusercontent.com/71908475/150387443-6980f145-ec65-461c-8793-7e387783ca25.png">

This is the effect of capacitors and diodes in the power supply circuit.
Battery voltage is polled after transmitter operation. In the pauses between transmissions, the battery restores the maximum voltage and charges the capacitors to the maximum value through leakage diodes. When a load is applied, the voltage drops and this drop depends on the load and the tasks performed by the processor.

**Comment by pvvx** [comment]
I don't speak English and it's hard for me to explain to you.
The impulse load in connection mode is less, because transmiting one frame in 2.5 seconds on one channel.
When working in advertising mode, 3 frames are sent on 3 channels. If the external device has active scan mode enabled, then this is a call to send another frame. Those. Immediately 3 or 4 gears, which has a difference in the supply voltage drop.

Launch https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
Click "Start Tx Measure" and open debug output to Chrome:
![image](https://user-images.githubusercontent.com/12629515/150485435-6cf8e203-3b2b-48d9-8144-94c0db39654d.png)

**Comment by pvvx** [comment]
CGG1 in the barn. [GraphMemo.html](https://pvvx.github.io/ATC_MiThermometer/GraphMemo.html)
![image](https://user-images.githubusercontent.com/12629515/150493585-0db12c96-d2be-4984-95dd-f40209ca2346.png)
![image](https://user-images.githubusercontent.com/12629515/150493622-59132ab3-5748-4f7c-a511-5867e85b9422.png)

**Comment by pvvx** [comment]
CGG1 https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html :
Vbat: 2895 mV
Vbat: 2909 mV
Vbat: 2910 mV
Vbat: 2901 mV
Vbat: 2896 mV
Vbat: 2896 mV
Vbat: 2892 mV
Vbat: 2907 mV
Vbat: 2903 mV
Vbat: 2895 mV
Vbat: 2921 mV
Vbat: 2918 mV
Vbat: 2911 mV
Vbat: 2908 mV
Vbat: 2894 mV
Vbat: 2907 mV
Vbat: 2898 mV
Vbat: 2901 mV
Vbat: 2921 mV
Vbat: 2907 mV
Vbat: 2911 mV
Vbat: 2908 mV
Vbat: 2918 mV
Vbat: 2902 mV
Vbat: 2893 mV
Vbat: 2891 mV
Vbat: 2915 mV
Vbat: 2895 mV
Vbat: 2909 mV
Vbat: 2908 mV
Vbat: 2907 mV
Vbat: 2908 mV

**Comment by pvvx** [comment]
Internal Power CGG1
Cycle between image changes on E-ink.
![image](https://user-images.githubusercontent.com/12629515/150498375-96238545-2884-4e5c-a825-115e2ab399e7.png)

**Comment by pvvx** [comment]
> That's only under 0.1V difference, which is actually quite excellent for this device in my opinion. ADC in ESP32 isn't "state of the art", you know. Good, stable ADC's are pretty expensive. ADC inside ESP32 is definitely only of average quality. It relies on internal voltage refefence, which can fluctuate with chip consumption and so you get varying ADC result. Then any external noise can be the "bad" factor... etc...

This is not an ESP8266/ESP32.
TLSR825x has a good and linear ADC with quality over 12 bits.

**Comment by pvvx** [comment]
> it looks the same on the new v3.5c :( <img alt="image" width="322" src="https://user-images.githubusercontent.com/71908475/150387443-6980f145-ec65-461c-8793-7e387783ca25.png">

The load on the battery for CGG1 and all with E-Ink is greater. It takes a lot of energy to redraw E-Ink. On the graph, the supply voltage drop reaches 0.2 Volts.
If the voltage was measured without redrawing E-Ink, then it will be 0.1..0.2V more. Approximately equal to the voltage of a loaded battery at 3 mA.
And the redrawing of the screen depends on the stability of the measured temperature and humidity. Voltage measurement together with the operation of the E-Inc driver chip will show 0.1..0.2V less. What we see.

**Comment by Protoncek** [comment]
>
> 
> This is not an ESP8266/ESP32. TLSR825x has a good and linear ADC with quality over 12 bits. The stability of the reference source for the ADC is also decent there.

Esp32 was just an example…
I worked with 12 and 16 bit ADCs and among others noise is a great pain in the ***. If, say, a designer doesn’t design PCB correctly a device can have unsolvable problems. GND plating is very important, and not making any loops…etc…
Other thing is, like you say, battery. I have quite a number of cheap batteries which with multimeter show appr. 3.2V, but when i put them, say, in BT button, or remote control (433MHz) it doesn’t work at all (not even for a short time!), because voltage immediately drops to almost zero when loaded with bigger current. In devices like this such batteries can work (if they have a capacitor inside), but above mentioned fluctuation can occur. I added two missing capacitors in all my xiaomi’s. One 20uF and one 100nF.
In this cases a quality battery is VERY important. And, these devices, imported from china have the cheapest “still working” batteries inside.

**Comment by pvvx** [comment]
The supply voltage has very high noise - the built-in DC-DC in the TLSR825x works, but this does not affect the ADC

**Comment by mmkrysiak** [comment]
Viktor, many thanks for the very good explanation. Because it's a hardware issue there's not so much to do left :(
I'll try to pass reports thru any min/max/median filter over some period of time to have more stable results.

**Comment by pvvx** [comment]
Can be bypassed by measurements when there is no E-Ink update:
![image](https://user-images.githubusercontent.com/12629515/150615908-84f1f15b-9928-4ab6-bd9e-1e1e2699731f.png)
Then the readings will be unrealistic. Refusal to work will occur already at 2.2V of such measurements.

**Comment by mmkrysiak** [comment]
@pvvx it's a very good idea. Battery level results are much more reliable for typical user now.
![image](https://user-images.githubusercontent.com/71908475/150639973-2ea9f443-827f-4b44-b9f2-1f5c763c1163.png)
but still need to be filtered to get stable results
<img width="467" alt="image" src="https://user-images.githubusercontent.com/71908475/150640899-9bc94fbc-e4d2-4993-b529-40f77be81981.png">

I'm just wondering: 
1. voltage report should be real. If someones decide to take a look on them would like to see reliable values
2. battery level should be stable, otherwise looks suspicious
Can you report battery voltage as it is but for the battery level calculations take only samples without E-lnk update additionally averaged in sliding window (5-7 samples)? 
@pvvx What do you think about this idea?

**Comment by pvvx** [comment]
CGG1_v35c_bat.bin + Passive BLE Monitor integration (default settings):
![image](https://user-images.githubusercontent.com/12629515/150693033-d0c067bb-ea57-49da-8370-3d08e7ea3404.png)
![image](https://user-images.githubusercontent.com/12629515/150693084-33686fb3-b2a4-461e-a6a1-55b043a15a4e.png)

**Comment by pvvx** [comment]
> 1. voltage report should be real. If someones decide to take a look on them would like to see reliable values

Not possible in principle due to the type of battery.
The voltage dependence of the battery type CRxxx is more than 15 mV per degree. Plus dependence on the discharge.
The new CR2032 on LYWSD03MMC is below 2.0V at -41°C.
The device does not have a current meter or a stable load to determine the internal resistance of the battery - the true remaining charge.
Both dependencies lead to very complex calculations and the result is not yet an indicator of the actual battery discharge.


> 2. battery level should be stable, otherwise looks suspicious

But this is reality.

**Comment by mmkrysiak** [comment]
Thanks @pvvx. Mine results are not that stable than yours but much better than before. Please insert changes into the general version for CGG1.
<img width="241" alt="image" src="https://user-images.githubusercontent.com/71908475/150697708-238b17cc-72d2-4f57-805b-3262e0367e51.png">

**Comment by pvvx** [comment]
It is possible that such a result was obtained due to the bit depth limitation in the format of advertising transmission you have chosen.
The integration calculates the percentage of the battery itself, according to the voltage values.
