### ISSUE TITLE
How to send display data?

### ISSUE THREAD

**Issue by unaiur** [pvvx/ATC_MiThermometer#187]
I have modified your firmware to support CGDK2 device, but I do not know yet the how the LCD memory is mapped to the segments in the LCD screen.

I was planning to use CMD_ID_LCD_DUMP to send different bit-patterns and identify each of the segments, but I cannot find any tool to send that command.

Is there any HTML page already prepared or should I modify some of the other pages?

**Comment by pvvx** [comment]
I usually insert a procedure that automatically moves the bit in the buffer after a couple of seconds and shoot the indicator on the camera.

**Comment by unaiur** [comment]
Thanks!

**Comment by pvvx** [comment]
DIY: CGDK2-2 + TB-04 (TLSR8253)
https://pvvx.github.io/CGDK2/CGDK2-2/
Added to main code and TelinkMiFlasher.html :)
