### ISSUE TITLE
[Feature request] Use hardware button to save energy

### ISSUE THREAD

**Issue by unaiur** [pvvx/ATC_MiThermometer#192]
Some devices (like CGDK2) have a hardware button that is currently unused.

It can be used to implement optional battery optimizations:

- Use a larger advertisement interval (1min), but when the button is pressed swap to a short advertisement interval (0.5sec) for 5 minutes or while there is an active BT connection. This mode can be enabled only for devices with a hardware button and for use cases that not require automated connections to the device. It can be also useful to speed up BT connections.

- Turn off the LCD until the button is pressed and then keep it on for a configurable time.

**Comment by pvvx** [comment]
To do this, you need to create another version. Software algorithms and functionality in the current version are not compatible with this implementation.
This is similar to the [XMWSDJ04MMC](https://pvvx.github.io/XMWSDJ04MMC/) variant. It showed inconvenience in use.

**Comment by pvvx** [comment]
> * Use a larger advertisement interval (1min), but when the button is pressed swap to a short advertisement interval (0.5sec) for 5 minutes or while there is an active BT connection. This mode can be enabled only for devices with a hardware button and for use cases that not require automated connections to the device. It can be also useful to speed up BT connections.

Preliminary analysis of CGDK2 consumption:
![image](https://user-images.githubusercontent.com/12629515/153693123-504c56d9-f078-4355-a9f6-57c21c6afd35.png)

**Comment by unaiur** [comment]
I don’t understand you. Are you saying it is worthless because the maximum
battery life with a CGDK2 always sleeping is 16 months?

Are you proposing to use a bigger battery? Maybe a CR2450 battery will fit
in.

Anyway, reducing the advertising time to less that half a second speed ups
the Bluetooth connection and makes it more reliable for Linux users.

Best regards!

**Comment by pvvx** [comment]
Yes. 
Sleeping TLSR8253 with RAM enabled consumes 3..3.1 uA. 
The transmission of advertising for approximately 10 seconds is added 3 μA.
The temperature sensor also consumes power. 
But the main consumer in CGDK2 is BU9792.

**Comment by unaiur** [comment]
I implemented the logic to turn on and off the lcd and its controller using the hardware button. Single click => toggles screen using an I2C command. I do not have hardware to measure the impact, but when the screen is off it takes around 25 seconds for the capacitor to drain and CPU to turn off, therefore the battery life should be greatly extended.

**Comment by mat-c** [comment]
How to you know when cpu turn off ? What is the time with lcd on ?

**Comment by pvvx** [comment]
Disabling the screen on CGDK2 is implemented in version 4.3
