### ISSUE TITLE
Debug firmware?

### ISSUE THREAD

**Issue by devbis** [pvvx/ATC_MiThermometer#196]
Is there a way to debug the firmware over UART? Is SWD pin can be used to print debugging information instead of just writing/reading firmware?
How do you debug your code on real hardware?

**Comment by pvvx** [comment]
By uploading new firmware.
The flashing time for SWS is 5 seconds.
I haven't used debuggers for a long time. Picking in the registers takes more time than new flashing.
For control, I use only PowerProfiler.
The device is always in sleep mode and leads to problematic debugging.

---
The SDK has an example of printf output on a any GPIO with a 2000000 baud UART.

**Comment by devbis** [comment]
I see, it is the more detailed solution. I was asking about the way to read UART prints.
Is it possible to use swire pin P14 (soldered for COM-UART flashing) to work as UART RX pin without resoldering, just reusing it in firmware?

**Comment by pvvx** [comment]
Yes, if configured in GPIO mode.
Then the SWS firmware will work after a RESET or a power cycle during activation.
