### ISSUE TITLE
Allow measuring interval to be a fraction of the advertising interval

### ISSUE THREAD

**Issue by metronidazole** [pvvx/ATC_MiThermometer#20]
With the web config page, it is not possible to set the measuring interval to be a fraction (e.g. 0.5) of the advertising interval.

It would be nice if this was made possible so the device can measure more frequently than how often it advertises via bluetooth

**Comment by pvvx** [comment]
Additional advertising does not save battery power. Percentage shares.

**Comment by pvvx** [comment]
The measurement quality of the sensor is poor. The reason is listed here https://github.com/pvvx/ATC_MiThermometer/issues/11#issuecomment-766776468
