### ISSUE TITLE
Thermometer LED display

### ISSUE THREAD

**Issue by joedupa** [pvvx/ATC_MiThermometer#200]
Is there any way to disable the "onboard" LED display for the Mi thermometer devices? I have several sensors that will be buried in the deep freezers and I will be accessing their readings remotely via external ESP controller. The intention is to preserve as much battery energy as possible. Thanks.

**Comment by pvvx** [comment]
Help solve these problems:
* Disabling the data refresh transmission command on the LCD does not save power.
* There is no documentation for LCD controllers.
* There is no command to switch the controller to low consumption mode.
* LYWSD03MMC uses more than 4 types of LCD controller chips.

**Comment by joedupa** [comment]
Thanks Victor, what is the operating voltage range of the LYWSD03MMC ? The 14335 battery is 3.6V as opposed to 3V CR2032, wouldn't this kill the sensor?

**Comment by pvvx** [comment]
[TLSR8251F512ET24](http://wiki.telink-semi.cn/doc/ds/DS_TLSR8251-E_Datasheet%20for%20Telink%20BLE+IEEE802.15.4%20Multi-Standard%20Wireless%20SoC%20TLSR8251.pdf): Supply voltage 1.8 - 3.6V
[SHT4x](https://sensirion.com/products/catalog/): Supply voltage 1.08 - 3.6V

**Comment by pvvx** [comment]
USB powered operation (5V):
![image](https://user-images.githubusercontent.com/12629515/155865454-3f027771-5c9e-4040-92cc-702cb3f0b4bb.png)
I do not recommend repeating, but if desired, it works with a slight increase in the total current consumption ... :)

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/155866344-98d015b8-786b-4485-80f3-ee949332edee.png)
![image](https://user-images.githubusercontent.com/12629515/155866389-ed93b3e6-245f-48e9-b0b0-8becda0acefa.png)
![image](https://user-images.githubusercontent.com/12629515/155866382-41423343-5c59-48b6-afff-d596e8afc0aa.png)
![image](https://user-images.githubusercontent.com/12629515/155866511-69d158b9-d5f1-4b34-8a7e-c7cb87ab4f28.png)

**Comment by joedupa** [comment]
Very informative Victor, thanks again, just ordered a couple of those: https://www.aliexpress.com/item/1005003637299772.html
