### ISSUE TITLE
Display component for esphome

### ISSUE THREAD

**Issue by puuu** [pvvx/ATC_MiThermometer#208]
Hi!
Thank you for the great custom firmware!

I created a display component for [esphome](https://esphome.io/). The pull request can be found at https://github.com/esphome/esphome/pull/3333 .

It also allows to synchronize the time.

After the pull request has been merged, it might be worth noting this in the documentation.

**Comment by ACrazyConcept** [comment]
That's pretty cool, will definitely have to try it out.
I imagine this could in principle also be possible directly from python on an RPi. Any thoughts on that?
