### ISSUE TITLE
[Feature request] Support for HHCCJCY01HHCC

### ISSUE THREAD

**Issue by miksumin** [pvvx/ATC_MiThermometer#210]
Hello, is it possible to add a support for Xiaomi Mi HHCC Flora Monitor (HHCCJCY01HHCC)?
https://xiaomi-rus.com/analizator_pochvy_i_osveshchennosti_xiaomi_smart_flower_monitor/

**Comment by pvvx** [comment]
From the only photo it looks like there is no Telink SoC.
https://fccid.io/2AJEPHHCCJCY01HHCC/Internal-Photos/Internal-Photos-3113860
I have no other information about HHCCJCY01HHCC.
