### ISSUE TITLE
Is it possible to get old passkey pin?

### ISSUE THREAD

**Issue by Heiko-L** [pvvx/ATC_MiThermometer#211]
Hi!
My problem is that i forgot my passkey but my phone is paired so I can enter the configuration page. But there is only an option to set the passkey- is it possible to get it?
TIA,
Heiko

**Comment by pvvx** [comment]
No. There is no such possibility.
Only by connecting the programmer and reading Flash.

**Comment by Heiko-L** [comment]
Oh, ok. Next time I'll write the passkey on the back :)
