### ISSUE TITLE
[Feature Request] LYWSD02 support

### ISSUE THREAD

**Issue by martini1992** [pvvx/ATC_MiThermometer#213]
Just wondering why the LYWSD02 isn't being supported, I'm aware that its OEM functionality works out of the box listening for the BLE messages but I was hoping for the extra customisability and battery life that this firmware provides. Also I've read that newer OEM firmware has started to remove functionality (battery level messages).

**Comment by pvvx** [comment]
[LYWSD02](https://pvvx.github.io/LYWSD02/)  - SoC Dialog Semiconductor DA14585.
For flashing need certificates...

**Comment by martini1992** [comment]
Ah right makes perfect sense thanks.
