### ISSUE TITLE
diabling Smiley -  setting always shows (   )  - MHO-C401

### ISSUE THREAD

**Issue by elbman** [pvvx/ATC_MiThermometer#214]
I'd like to disable the smiley on my MHO-C401's (8x) but unfortunately the brackets are still there.

I think setting does not work on MHO-C401.

Backets are always shown, even when you select a smiley without them.

Hope you can fix it

![401](https://user-images.githubusercontent.com/36014482/165165599-afbd3100-60e1-433e-a6cd-2eab611f0f93.jpg)

**Comment by elbman** [comment]
my configuration:

06:30:53: New custom config: [1, 0, 0, 0, 40, 8, 174, 124, 199, 129, 30]
06:30:53: Settings 55010000002808AE7CC7811E was send successful
06:30:54: Hardware Version: MHO-C401 V_14, Software Version: 3.7, Sensor: SHTC3
06:30:54: Custom config: [1, 0, 0, 0, 40, 8, 174, 124, 199, 129, 30]

**Comment by pvvx** [comment]
The E-ink display has combined segments:
![image](https://user-images.githubusercontent.com/12629515/165874074-1ce983ce-4afa-4c7f-9ffc-d9fa3679d096.png)
https://github.com/znanev/MHO-C401

**Comment by elbman** [comment]
👌 I got it, thanks for the hint
