### ISSUE TITLE
LYWSD03MMC Custom Firmware Version 3.7 (HW: B1.4, B1.6, B1.7, B1.9, B2.0) not found

### ISSUE THREAD

**Issue by p-ranjan** [pvvx/ATC_MiThermometer#215]
Hi,
could anyone refresh the link for the custom Firmenware of LYWSD03MMC. It seems to be done. 

Thanks

**Comment by pvvx** [comment]
These files are automatically loaded into [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html). No download required.

**Comment by p-ranjan** [comment]
On my device i don't see then flash custom firmware button. The only option is to upload it. I need the bin file to flash my temperatur sensor.

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer#firmware-binaries
