### ISSUE TITLE
TX Power: What means VANT vs VBAT 

### ISSUE THREAD

**Issue by pedrobsm** [pvvx/ATC_MiThermometer#22]
When I try to set the TX power to any VBAT value (>+3.01), it reverts to VANT-25.18 dbm.
What does it means?
I need to increase the TX power to make the signal more stable. Any suggestion?

Thanks.

**Comment by pvvx** [comment]
VBAT does not work on Xiaomi LYWSD03MMC PCB without tweaks.

**Comment by pedrobsm** [comment]
Ok. Can you tell me what are the tweaks? :)
My sensor is close to a 3,3v power supply, from the previous wired sensor :)
