### ISSUE TITLE
Telink Flasher does not really disconnect

### ISSUE THREAD

**Issue by cimm** [pvvx/ATC_MiThermometer#220]
Telink Flasher webpage on Chrome 101.0.4951.64 (Fedora Linux 35).

I flashed the Mi thermometer with the custom firmware a while back. Easy. I can now connect via the flasher and change the settings. When done, I disconnect via the "Disconnect" button at the top of the Telink Flasher webpage, but the bluetooth icon on the Mi thermometer doesn't go away.

Running `bluetoothctl` after having disconnected via the flasher confirms the device is still connected. I can disconnect from `bluetoothctl` after which the bluetooth icon on the Mi thermometer does indeed turn off. It looks like the disconnect button does not work. It shows up in the log, there are no errors in the Chrome console, but I don't think it does disconnect.

After having connected with the flasher for a first time, the flasher no longer connects until I reboot the computer, but that looks like a different issue?

Minor issues, everything works the thermometer is announcing the data as expected, just some quality of life improvements. The OTA flashing was extremely easy. Thank you!

**Comment by pvvx** [comment]
This refers to Chrome's implementation of the Web Bluetooth API on Linux.
