### ISSUE TITLE
Question: android command line app or with mqtt support?

### ISSUE THREAD

**Issue by olivluca** [pvvx/ATC_MiThermometer#224]
Is there an android command line app that can be used to scan for the beacons? 
Alternatively is there an app that can read the temperature and humidity and sends it via mqtt?
I'm trying MijiaTemp but it only has support for thingspeak (besides, it's currently reporting 525.8ºC 😲).

**Comment by pvvx** [comment]
?
![image](https://user-images.githubusercontent.com/12629515/173862913-72a12c18-a44d-478c-80fb-2ed253cc5c10.png)

**Comment by olivluca** [comment]
![image](https://user-images.githubusercontent.com/8250980/173874722-b7247ea1-2643-4c10-bce8-d0131029fbbb.png)

**Comment by olivluca** [comment]
I any case, even when it reads correctly, it doesn't support mqtt (though I'd prefer a command line utility and see the raw beacon)

**Comment by pvvx** [comment]
In thermometers, user software uses 8 advertising formats. Switching is given in [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html).

**Comment by paolo-caroni** [comment]
There is https://github.com/G0RIAN/MijiaLogger but support only LYWSDCGQ

**Comment by paolo-caroni** [comment]
Ok, there is also a fork that support mijia with ATC firmware https://github.com/bartashevich/MijiaLogger
