### ISSUE TITLE
Addition: two images of the packaging for the Xiaomi Mijia LYWSD03MMC info page

### ISSUE THREAD

**Issue by moritz-john** [pvvx/ATC_MiThermometer#226]
Hello,

here are two images for the this site: https://pvvx.github.io/ATC_MiThermometer/ (only if needed)

I was unsure if I was buying the right version.
Turns out it was the right thermometer, so I wanted to add two more images of the packaging to make it easier for other people.
![LYWSD03MMC_package_2](https://user-images.githubusercontent.com/70295002/175375438-0f3eb5c0-87f9-49a8-b012-a4a9f8b2f2ec.jpg)
![LYWSD03MMC_package_1](https://user-images.githubusercontent.com/70295002/175375443-0a081343-b0a7-46be-a146-8f1f4efe477b.jpg)

Kind regards.

**Comment by pvvx** [comment]
The current firmware supports all the Xiaomi Mijia LYWSD03MMC released. There is no need to choose a production date and packaging options.

**Comment by moritz-john** [comment]
> The current firmware supports all the Xiaomi Mijia LYWSD03MMC released. There is no need to choose a production date and packaging options.

To put it differently: I bought mine from here: https://www.amazon.de/gp/product/B08C7KVDJW/ and on the product page `LYWSD03MMC` is not mentioned even once. So at least for me a photo of the front packaging would have been helpful.

**Comment by nagyrobi** [comment]
Same here. They are listed by the SKU number in the shops (NUN412...). Searching by term LYWSD03MMC doesn't bring up the product in webshops around here.

**Comment by moritz-john** [comment]
Yes, they just listed as Xiaomi `Mi Temperature and Humidity Monitor 2`.
