### ISSUE TITLE
devices canot connect mihome APP

### ISSUE THREAD

**Issue by 836154942** [pvvx/ATC_MiThermometer#227]
Xiaomi Mijia (LYWSD03MMC)。

flashed the framework，can normal displace on the device，but can't connect  to mihome app，and   on the https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html   ，  also can't connect bluetooth and config,  connect logs:

10:11:55: Searching for devices
10:12:01: Connecting to: ATC_66E97A
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Reconnect 1 from 5
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Reconnect 2 from 5
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Reconnect 3 from 5
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Reconnect 4 from 5
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Reconnect 5 from 5
10:12:12: Hardware Revision String: B1.4
10:12:12: Detected Mi device
10:12:12: NotSupportedError: GATT operation failed for unknown reason.
10:12:12: Something went wrong, too many reconnects

what should i do ,

**Comment by pvvx** [comment]
This is an alternative firmware to work in Home Assistant and other open-source projects, and not for the proprietary MiHome.
