### ISSUE TITLE
Частота отправки данных датчиком.

### ISSUE THREAD

**Issue by centurion800** [pvvx/ATC_MiThermometer#235]
Привет. Есть 5 датчиков LYWSD03MMC которые вяжутся к xiaomi gateway 3. Не устраивала частота опроса датчиков. Перепрошил один Вашей прошивкой, все супер.. было.. первый час. Переодически начали отваливаться остальные (не прошитые) датчики, до этого полгода ни одного отвала не было. Перемещал гейт, менял батарейки в датчиках,.. Не оно. Возможно gateway не тянет такую нагрузку. Где можна увеличить интервал между отправками данных?

**Comment by pvvx** [comment]
Какой сервер используется? Китайский?
К примеру LYWSD02 передает новые данные раз в десять чаще и ничего описанного вами не происходит.
Не так давно китайский сервер у меня вообще отвалился и потерял все регистрации...
Так-же об сбоях при использовании китайского сервера сообщают и другие на 4pda...
