### ISSUE TITLE
zigbee

### ISSUE THREAD

**Issue by learner996** [pvvx/ATC_MiThermometer#238]
How to flash to zigbee protocol

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/221#issuecomment-1279855367

**Comment by jagheterfredrik** [comment]
@pvvx continuing the discussions from https://github.com/pvvx/ATC_MiThermometer/issues/221#issuecomment-1279855367

Are you saying to call blc_ota_setNewFirmwwareStorageAddress to extend the flash size to allow for the larger firmware or what do you mean by "The first block is to change the Flash markup for OTA with ZigBee"?
