### ISSUE TITLE
[feature request] The battery sensor attribute.

### ISSUE THREAD

**Issue by sp7dpt** [pvvx/ATC_MiThermometer#243]
The battery sensor has a battery health percentage, but has no battery attribute in the list. Can you add it?
![temp](https://user-images.githubusercontent.com/54576080/187073980-d835dbdc-3789-4941-bbb9-d195be5a8709.png)

**Comment by Protoncek** [comment]
What do you mean? It clearl states “device_class” as battery and “unit of measurement” as %…

**Comment by sp7dpt** [comment]
Other sensors in Home assistant have a battery attribute.
For example, the Zigbee motion sensor

![zigbee sensor](https://user-images.githubusercontent.com/54576080/187087395-2529910e-c0e1-457f-be13-7f14104450a0.png)

I have automation that polls all battery-powered sensors and sends notifications about low battery.

**Comment by Protoncek** [comment]
I don’t see any practical reason why you’d have two exactly same values in one sensor. In your example you also have 77.5 value as “state”. Why again same state as attribute? (Just wondering…)

**Comment by sp7dpt** [comment]
It seems to be a standard. See the integration that shows the battery status https://github.com/maxwroc/battery-state-card
It is based on the battery attribute and my my automation too.

**Comment by Protoncek** [comment]
Hm...
i installed above addon for test and my 8 xiaomi's thermometer batteries show perfectly in this card even without "battery" attribute. I think that "attribute" setting in this card is just an option, if battery state is not defined in "main state". 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/26406640/187088339-9ca3361e-8bdd-4b74-bd34-7348c60b0bb2.png">
<img width="740" alt="image" src="https://user-images.githubusercontent.com/26406640/187088428-594924f0-2123-4308-97c7-cd06fa4c9ee8.png">

**Comment by sp7dpt** [comment]
OK, maybe that's a bad example. I just wanted to show you that the sensors have duplicate values. I do not know why.
Another example of an Aqara sensor
![aqara](https://user-images.githubusercontent.com/54576080/187088913-1d3445d5-a611-4d18-abae-49de09056e03.png)
