### ISSUE TITLE
Unable to connect due to the change of the device known ID

### ISSUE THREAD

**Issue by amossssss** [pvvx/ATC_MiThermometer#245]
After flashing the custom firmware, I found that the device known ID had changed, resulting in authentication failure. flashing back the official firmware can not modify the original device known ID. Is there any way to modify the device known ID?
The have changed the device known ID
![屏幕截图 2022-09-04 131719](https://user-images.githubusercontent.com/61683025/188298612-ff76071a-dea8-4755-a065-e70aba348d7a.png)

This is the original ID:
![屏幕截图 2022-09-04 133438](https://user-images.githubusercontent.com/61683025/188299078-ea5dc0ca-b246-42c0-884a-5d3590405ba7.png)

Same problem:https://github.com/atc1441/ATC_MiThermometer/issues/207
https://github.com/atc1441/ATC_MiThermometer/issues/185

**Comment by pvvx** [comment]
You will need to make up to 4 attempts to register in MiHome and everything will work.
