### ISSUE TITLE
Unable to connect anymore to LYWSD03MMC after changing Advertising interval

### ISSUE THREAD

**Issue by csr40** [pvvx/ATC_MiThermometer#25]
Hello,

I set "Advertising interval" to 10000 (I did it on 2 devices) and now I'm unable to connect anymore to the thermometers (via TelinkMiFlasher).
Is there any way to reset settings of the thermometer with firmware version 1.6? I tried to short reset pins but with no effect.

Thank in advance for your help,
Best Regards

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/105694634-3816cb00-5f12-11eb-932d-3f18ea0308e3.png)

Windows 10 + USB-BT very low cost adapter CSR8510 (A10,,, MSFT100)
Drivers:
![image](https://user-images.githubusercontent.com/12629515/105694613-351bda80-5f12-11eb-9247-e8240b75e665.png)
```
Log:
13:25:32: Searching for devices
13:26:17: Connecting to: ATC_0B5EED
13:26:25: NetworkError: Connection failed for unknown reason.
13:26:25: Reconnect 1 from 5
13:26:41: Detected custom Firmware
13:26:41: Hardware Version: LYWSD03MMC.
13:26:41: Software Version: 1.6, Custom config: [6, 0, 0, 0, 160, 4, 191, 124, 49]
```
160 * 62.5 = 10000 ms

LowCost Android Phone:
```
Log:
13:38:24: Searching for devices
13:38:39: Connecting to: ATC_0B5EED
13:39:06: Detected custom Firmware
13:39:06: Hardware Version: LYWSD03MMC.
13:39:06: Software Version: 1.6, Custom config: [6, 0, 0, 0, 160, 4, 191, 124, 49]
```

**Comment by pvvx** [comment]
nRF Connect.
Set default settings:
![image](https://user-images.githubusercontent.com/12629515/105698232-a8bfe680-5f16-11eb-81fb-cd663b3c049c.png)
![image](https://user-images.githubusercontent.com/12629515/105698241-abbad700-5f16-11eb-8bf9-57d207603e42.png)

**Comment by csr40** [comment]
Thank you very much Victor!
I used nRF (android phone) with your tips and now I can connect to my thermometers again.

You are great, all the best for you :-)!
