### ISSUE TITLE
LYWSD03MMC HW

### ISSUE THREAD

**Issue by kazuser** [pvvx/ATC_MiThermometer#251]
Hi!

Could you please tell me where I can see/find HW version for my LYWSD03MMC?
![image](https://user-images.githubusercontent.com/3335273/191199184-e4a9539a-d590-482e-981b-5fba6de853a7.png)

**Comment by pvvx** [comment]
It is possible to set the version number according to the release date indicated on the box.
By comparing with the batch date for those who have already flashed an alternative firmware.
