### ISSUE TITLE
Can't light up the screen correctly after replacing the temperature sensing chip

### ISSUE THREAD

**Issue by ZdDroid** [pvvx/ATC_MiThermometer#254]
The printed version number of the motherboard is: B1.4

After replacing the temperature sensing chip with SHT3C waterproof type, the firmware is recognized as B1.6 after brushing in the custom firmware, the LCD can not be displayed, Bluetooth is normal, temperature sensing is normal.
When I remove the temperature sensing chip, the LCD can be displayed normally as B1.7.

Status: Hardware Version: LYWSD03MMC B1.7, Software Version: 3.8
Vbat: 3286 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 0, flg: 0x01:r1/t0

-- Whether to consider adding a custom HW function?

When I re-solder the temperature sensing chip SHT3C, the LCD will not show again.
Status: Hardware Version: LYWSD03MMC B1.4, Software Version: 3.8
Temp/Humidity: waiting notify for data after connecting

**Comment by pvvx** [comment]
The version is determined by the addresses of the display and sensor on I2C

HW | LCD I2C   addr | SHTxxx   I2C addr | Note
-- | -- | -- | --
B1.4 | 0x3C | 0x70   (SHTC3) |  
B1.6 | UART! | 0x44   (SHT4x) |  
B1.7 | 0x3C | 0x44   (SHT4x) | Test   original string HW
B1.9 | 0x3E | 0x44   (SHT4x) |  
B2.0 | 0x3C | 0x44   (SHT4x) | Test   original string HW

Version 1.7 or 2.0 is determined at first run by reading the HW line written in Flash.
Display matrices are different for all versions.

---

Users who can solder microcircuits can change and assemble the required version of the program themselves.
The introduction of additional flags and options increases the size of the code, battery consumption and introduces uncertainties - additional errors and questions from users with the wrong choice...
