### ISSUE TITLE
Activation doesnt work

### ISSUE THREAD

**Issue by domoZAM** [pvvx/ATC_MiThermometer#256]
Hi, I tried to use the web Flasher with my sensor, I can connect to it but when i push "Do Activation"  stay in wait and don't evolve from this.. (see the screenshot attached)
![Immagine](https://user-images.githubusercontent.com/76051127/195379675-7f371ca7-229a-489e-9c63-226f7473cc50.jpg)

Any suggestion ?
Thanks in advance for attention
Marco

**Comment by Blackshome** [comment]
did you enable-experimental-web-platform-features? links for chrome, opera & edge are on that page.

**Comment by EnerGeh** [comment]
Same here, tried this with Bromite on android and vivaldi on linux. Device is a Qingping CGG1 2022. May I provide some logfiles (which ones?) for your investigation in this?

**Comment by TheZoker** [comment]
Same issue here

**Comment by TheZoker** [comment]
After some research, this fixed the issue for me (at least for me CGG1):
https://github.com/pvvx/ATC_MiThermometer/issues/41#issuecomment-830570681

**Comment by domoZAM** [comment]
Unfortunaly my device don't have button at all..

**Comment by EnerGeh** [comment]
> After some research, this fixed the issue for me (at least for me CGG1): [#41 (comment)](https://github.com/pvvx/ATC_MiThermometer/issues/41#issuecomment-830570681)

What a great finding! This works for me with the CGG1 2022 - Thanks! @pvvx maybe you can add this in the manual for the CGG1 2022?

**Comment by pvvx** [comment]
> maybe you can add this in the manual for the CGG1 2022?

There are still many uncertainties in Bluez, plus there is an experimental mode... Bluez is being actively changed and I cannot specify what needs to be done for each version of Bluez.
