### ISSUE TITLE
Unique chip ID of Tlsr8258

### ISSUE THREAD

**Issue by McuMirror** [pvvx/ATC_MiThermometer#259]
Dear Victor,
Please advise how to read 4-byte chip Unique ID of Tlsr8258.
I want to use this id in Ble mac address.
Chineese datasheet and sdk not contain any information about it. or i couldn't find it :)

**Comment by pvvx** [comment]
TLSR825x does not have a "**Unique** Chip ID".
There is **Chip ID**: 0x5562 and **rev**: 0x02. Same for all TLSR825x (TLSR8251, TLSR8253, TLSR8258)
Flash has a **UID**.
[Sample read in TLSRPGM](https://github.com/pvvx/TLSRPGM#samples).
