### ISSUE TITLE
LYWSDCGQ 'Not found Telink OTA service!'

### ISSUE THREAD

**Issue by Stolz** [pvvx/ATC_MiThermometer#262]
Hi.

First of all thanks to @atc1441 and @pvvx for the awesome software and firmware.

I purchased from the official Xiaomi physical store at Hong Kong what I think is a  LYWSDCGQ sensor (round body, lcd display). It has the original Xiaomi firmware (version 1.0.1_0068 according to Mi Android app) and it announces itself as MJ_HT_V1 with MAC '4C:65:A8:...'.

I want to flash PVVX custom firmware but when I try to connect with TelinkMiFlasher, I get this message:

    12:24:09: Searching for devices
    12:24:22: Connecting to: MJ_HT_V1
    12:24:24: Not found Telink OTA service!
    12:24:24: Disconnected.
    
 Does that mean the sensor is not supported?. Is there anything I can do?
 
 Thanks

**Comment by pvvx** [comment]
Only Xiaomi thermometers with Telink SoC are supported.
