### ISSUE TITLE
MiFlasher 4.4 disconnects after 10 sec

### ISSUE THREAD

**Issue by rudivandrunen** [pvvx/ATC_MiThermometer#269]
running on an M1 mac in chrome 96.0.4664.110 on 12.5 I can connect to my Xiaomi Mijia (running 3.7 f/w, updated on other machine)) for just 10 sec, after that the flasher disconnects. Anyone has seen this before ? Any fix ?

**Comment by rudivandrunen** [comment]
might be duplicate of https://github.com/pvvx/ATC_MiThermometer/issues/231 will check

**Comment by pvvx** [comment]
For reliable connection and refirmware on LYWSD03MMC, the battery level must be more than 40%. This is a design feature - a cheaper version of the hardware.
