### ISSUE TITLE
'send settings to custom firmware' not working as expected

### ISSUE THREAD

**Issue by gumby2** [pvvx/ATC_MiThermometer#274]
tried putting "146, 96, 0, 0, 40, 4, 63, 124, 49, 5, 60" into the fied for tx power (63 = 10db) and clicking send, a subsequent 'get config' doesn't show any change.  should this work?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/121#issuecomment-1334084410
