### ISSUE TITLE
Custom FW and Xiaomi ZNDMWG02LM

### ISSUE THREAD

**Issue by KITT3000** [pvvx/ATC_MiThermometer#278]
Is it possible to connect these temperature sensors with custom fw to the ZNDMWG02LM gateway? I have this gateway and 11 sensors and in the modded Mi Home app I have this hooked up, but unfortunately the sensors are overstating the temperature so I wanted to use custom fw, but I don't know if there will be any way to preview it as it is now.

**Comment by pvvx** [comment]
Read the title https://github.com/pvvx/ATC_MiThermometer
_Custom firmware is not supported in MiHome. But it is possible to work LYWSD03MMC with 'Xiaomi Gateway 3' by first registering in MiHome on the official firmware, flashing to custom firmware with restoring the binding key from MiHome, replacing the device name with "LYWSD03MMC" and setting the advertising type to "MIJIA (MiHome)" marked "encrypted"._
