### ISSUE TITLE
Support for XIAOMI Mijia Bluetooth Thermometer 3?

### ISSUE THREAD

**Issue by PetrMa** [pvvx/ATC_MiThermometer#279]
Hello,

do you plan to support new XIAOMI Mijia Bluetooth Thermometer 3?

Thanks

**Comment by pvvx** [comment]
Mijia Smart Thermometer 3 - id: MJWSD05MMC - The chipset is still unknown.
Alternative firmware is only supported on thermometers with Telink SoC (TLSR825x).
The rest of Xiaomi works in Mijia format, at https://github.com/custom-components/ble_monitor.

**Comment by pvvx** [comment]
https://pvvx.github.io/MJWSD05MMC/

**Comment by Rushmed** [comment]
Hi,

I am able to connct my MJWSD05MMC but I get stck on `Activating now, please wait...`
Any hint?

**Comment by pvvx** [comment]
Use the side button to switch the sensor to pairing mode, the Bluetooth icon will flash on the screen.

**Comment by Rushmed** [comment]
Thans it worked.

**Comment by pvvx** [comment]
Full support of MJWSD05MMMC in version 4.2.

**Comment by maiandrei** [comment]
> Hi,
> 
> I am able to connct my MJWSD05MMC but I get stck on `Activating now, please wait...` Any hint?

Hi, and many thanks for your great work!
I am also stuck with `Activating now, please wait...`, despite the fact I am connected to the device and it shows
Status: 'MJWSD05MMC HW:V2.3' connected, you can now Do the Activation to either get the Token or flash a new Firmware
Temp: 20.2°C, Humi: 45%, 3179 mV

Initially the BT icon flashes, but as soon as I connect to device it is steady on.

Could be the HW:V2.3 an issue?

**Comment by pvvx** [comment]
The button was pressed at the wrong time or in the wrong sequence...
