### ISSUE TITLE
Showing NaN

### ISSUE THREAD

**Issue by abonforti** [pvvx/ATC_MiThermometer#28]
I have flashed 4 thermometers with this tool which works great, but I think I need some suggestions in the parameters to set while flashing.
Randomly, the thermometers, starts to show NaN to my Home Assistant instance, I believe they lost connection. It's not a range issue, since atm, one thermometers just 20cm above the usb bluetooth key is showing NaN, while one other two rooms far is showing the correct temperature.
What can cause this issue? Should I increase the range via the flasher tool? Attaching a screenshot for reference.

![Screenshot 2021-01-26 at 09 32 29](https://user-images.githubusercontent.com/38355294/105820197-86cb7000-5fb9-11eb-8399-bdeedf734aae.png)

**Comment by pvvx** [comment]
> What can cause this issue? 

Home assistant and his equipment with settings.
