### ISSUE TITLE
Backup pervious firmware

### ISSUE THREAD

**Issue by yousaf465** [pvvx/ATC_MiThermometer#280]
How to backup the pervious firmware? I have one thermometer running since 1 year, now I want to update to latest 3.9 version how to backup pervious firmware?

**Comment by pvvx** [comment]
Hardware programmer...

**Comment by pvvx** [comment]
All firmware versions are in the repositories.
Old versions are available at [releases](https://github.com/pvvx/ATC_MiThermometer/releases)
