### ISSUE TITLE
LYWSDCGQ/01ZM support?

### ISSUE THREAD

**Issue by yousaf465** [pvvx/ATC_MiThermometer#281]
Is this model (LYWSDCGQ/01ZM) supported? It is driven by a AAA battery. https://www.xiaomistore.pk/mi-bluetooth-temperature-humidity-monitor.html

**Comment by pvvx** [comment]
What chip is in this sensor?

**Comment by yousaf465** [comment]
https://esphome.io/components/sensor/xiaomi_ble.html#lywsdcgq this is the model and how do I know it's chip in this sensor?

**Comment by schilea** [comment]
Maybe you can figure it out from here https://www.youtube.com/watch?v=POuOTai1Q1E&ab_channel=anatolxxx

**Comment by mat-c** [comment]
It is a nRF51802 QFAA.
see https://twitter.com/NZSmartie/status/1123519600325316608
https://github.com/NZSmartie/MeshTemp

**Comment by pvvx** [comment]
In this repository, I include only thermometers with [Telink](https://www.telink-semi.com/) chips in support.
