### ISSUE TITLE
How to use "Send settings to custom firmware"

### ISSUE THREAD

**Issue by incaqueen** [pvvx/ATC_MiThermometer#282]
Hi, can't seem to find a way to manage create a template. I tried to copy the Custom Config [163,96,0,0, etc.] in the send settings, but it doesn't work.

I'd like to have 1 config that I can apply to all devices (so I don't have to reselect each option). Any suggestions?

**Comment by pvvx** [comment]
ID Command "Get/set device config": 0x55
"Get device config" - 0x55
"Set device config" - 0x55[,data]
data = [struct cfg_t](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/app.h#L29)

**Comment by incaqueen** [comment]
Awesome. Works really well for managing the 10+ sensors I've flashed.
