### ISSUE TITLE
Battery reporting issue after updating to 3.9

### ISSUE THREAD

**Issue by gminadak** [pvvx/ATC_MiThermometer#286]
Hello.
First of all thank you for all the effort you have put in this project.
After upgrading to firmware 3.9 I see that the battery level is at 100% for both of my thermometers.
Before the one of them was at approximately 80%.
I'm using the BThome integration with an on board BTdevice(Laptop).
![bedroom](https://user-images.githubusercontent.com/45330594/212829511-d321e0d4-8cc7-488b-ad08-eeb25898f906.png)
![bedroomgraph](https://user-images.githubusercontent.com/45330594/212829518-1807f0c8-fd5e-4073-979d-e776b44df7ff.png)

**Comment by pvvx** [comment]
The correction is made taking into account the characteristics of CR2032 and similar elements.
A new battery without load puts out more than 3 volts. At light load, during the first days, the voltage drops to about 2.9 V and this continues for 80-90% of the battery life. Two years of experience in the operation of thermometers led to the fact that
readings need to be corrected.

**Comment by gminadak** [comment]
@pvvx
> Your battery is draining too much. This indicates that you are using a BTHome with "active scanning" or poor quality batteries.
The battery's is what came with the device.
I see under Bluetooth integration on HA that "Passive scanning" is not selected.
Do you suggest to enable it?
![image](https://user-images.githubusercontent.com/45330594/212989077-4985a7f3-4ce9-4d3e-8e4e-47f7e379708d.png)

**Comment by pvvx** [comment]
Active scanning requires the device to respond. This is additional consumption. In addition, there is a constant overwriting of files on the disk, which renders the SSD unusable.
In the current implementation of BTHome, not all devices work in the "passive scan" mode.
To work with BTHome in passive mode, you need to enable "AdFlags" in TelinkMiFlasher:
![image](https://user-images.githubusercontent.com/12629515/213009606-d440f960-0d0a-4372-82e5-3c51771060a5.png)

**Comment by gminadak** [comment]
I have enable "passive scan" and AdFlags, the only BT device's I'm using is this two thermometers for now.
It looks like the BThome wasn't the best choice after all, I will look for other options.
Thank you for the help.
