### ISSUE TITLE
SJWS01LM support?

### ISSUE THREAD

**Issue by ilgrank** [pvvx/ATC_MiThermometer#287]
Hi
I see that only thermomethers are supported by your firmware, but in [TelinkMiFlasher code here](https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html) there's mention of **SJWS01LM** between the known device ids.
It is supported for Mi-binding only, right?
Do you know if it will be possible to flash it in the future or it does have a different chipset?
There's an interesting discussion about the data payload here:
[https://github.com/custom-components/ble_monitor/issues/181](https://github.com/custom-components/ble_monitor/issues/181)

**Comment by alessocci** [comment]
I too would be very interested in the future implementation of the SJWS01LM flood detector.
Thanks

**Comment by pvvx** [comment]
This requires a hardware revision of the thermometer - external contacts and sealing of the case. Other than that, no problem...

**Comment by ilgrank** [comment]
@pvvx : I can offer support for users, I do speak english and I'm willing to help

**Comment by pvvx** [comment]
@ilgrank - Для создания прошивки и программного обеспечения к нему необходимо иметь сам SJWS01LM. У меня его пока нет.
И в стадии разработки альтернативной прошивки сейчас находится [MJWSD05MMC](https://pvvx.github.io/MJWSD05MMC/). Он тоже имеет отличия с текущими термометрами. Сделать всё универсальное одному сложно - это требует много времени. 
И, если создавать совместную поддержку пользователей, то потребуется не только знание разных языков, но и опыт эксплуатации, тестов и доработки программного обеспечения для поддерживаемых датчиков. Я не против объединиться, но ещё не имею достаточного опыта совместной работы в github.

**Comment by ilgrank** [comment]
@pvvx Привет
Что касается одного, я могу купить его и отправить на ваш адрес, если вы предоставите его мне в частном порядке.
Я не программист, но могу помочь вам ответить на некоторые вопросы. Конечно, у меня нет вашего представления о коде, поэтому, возможно, я могу выступать только в качестве первого уровня поддержки.
Я спросил вас, собираетесь ли вы его поддерживать, так как с первого взгляда мне кажется, что это просто термометр МИ без датчика температуры/влажности и показания реле (я имею в виду, что вы уже внедрили 90% код уже для этого)
Дайте мне знать, если я могу быть чем-то полезен

**Comment by pvvx** [comment]
Я уже заказал SJWS01LM на https://aliexpress.com/item/1005001814960091.html
Обычно доставка составляет 3..4 недели.

**Comment by ilgrank** [comment]
Это отличная новость, я буду следить здесь, если я могу чем-то помочь, просто @упомяните меня, и я свяжусь с вами
спасибо

**Comment by pvvx** [comment]
The case is not disassembled - on glue.
https://pvvx.github.io/SJWS01LM/

**Comment by ilgrank** [comment]
Thanks for dissecting it!
I also seen you added support for it in Telink Flasher.. so it is very similar to other ATC devices after all?

**Comment by ilgrank** [comment]
> The case is not disassembled - on glue. https://pvvx.github.io/SJWS01LM/ ![image](https://user-images.githubusercontent.com/12629515/223366927-bf225ed5-b106-4372-970b-a24e0326b378.png)

Hi @pvvx , has there been any progress on SJWS01LM?
I seen you merged #310 some time ago, if I understand correcty, battery level can be read, but alarm can not, right?
Thanks!
