### ISSUE TITLE
Esphome display problem

### ISSUE THREAD

**Issue by cop98** [pvvx/ATC_MiThermometer#288]
Hi,

I am using this component expose https://esphome.io/components/display/pvvx_mithermometer.html
To display some data on the display. The problem is that the screen keeps updating, showing the original temperature and only occasionally the data received from esphome.

Is it possible to create a feature so that the display does not update and only displays the values received from esphome?

Thank you

Translated with www.DeepL.com/Translator (free version)

**Comment by pvvx** [comment]
I do not support ESPHome
