### ISSUE TITLE
Offer BLE device name prefix filter for GraphMemo pages etc. or accept device name argument?

### ISSUE THREAD

**Issue by nealmcb** [pvvx/ATC_MiThermometer#292]
The [Telink Flasher](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) web page has a very helpful BLE device name prefix filter. My environment is filled with dozens of Bluetooth devices named GJ1e5d56cd7d, so I always have to scroll around in the Connect popup box to find what I'm looking for. Could we get such a filter added to some of the other pages with a Connect button, like [GraphMemo](https://pvvx.github.io/ATC_MiThermometer/GraphMemo.html), making it easy to filter out the stuff we aren't interested in?

Or could we have a URL query option to specify a given device name so we don't have to enter the name at all?

And many thanks for this incredible interface to an amazingly cheap and powerful device!

**Comment by pvvx** [comment]
ok
