### ISSUE TITLE
Random temperature spikes on HA

### ISSUE THREAD

**Issue by EndermanAPM** [pvvx/ATC_MiThermometer#293]
Good afternoon, 

I've installed your custom firmware on my thermometers but on HA i keep seeing this random spikes on temperature.
I'm unsure where the problem lies, but hopefully you will be able to tell me what door to knock. Thanks.

![image](https://user-images.githubusercontent.com/3709362/216612062-44dcb6da-82b0-4331-a9b8-0435c86cc558.png)

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/271

**Comment by EndermanAPM** [comment]
Thanks!
