### ISSUE TITLE
Flashing and connecting is stable, advertising not working

### ISSUE THREAD

**Issue by rjvtww** [pvvx/ATC_MiThermometer#295]
I got a brand new LYWSD03MMC B1.7, and flashed it first with ATC1441, after which I realised that pvvx was newer and flashed it with that one.

Process went fine (OTA), and connecting to the device is stable and I can change settings. The only setting I changed was the advertising format to ATC1441. Sadly I cannot pick up any advertising, either using my RPI setup or using the HTML tool (using the same pc and bt adapter that I use to connect and flash the device).

Any thoughts on what I can check?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/218549278-da09cc69-e113-4d95-bbec-2e355496baf5.png)

**Comment by rjvtww** [comment]
Can you explain what does AdFlags do?

Thanks!

**Comment by pvvx** [comment]
Enables additional flags in the ad pack and battery consumption increases.
This option is made to support older third party programs...

**Comment by rjvtww** [comment]
I was able to get it working, but on my setup (RPI4, node red), I get a fixed value for a long time, as if the signal was not changing at all. Here is a screenshot of the last 24 hours as an example.

![image](https://user-images.githubusercontent.com/69891597/219812786-12bca05c-2ab5-4d53-8dd1-f668df83f65c.png)

**Comment by pvvx** [comment]
I don't have an RPi4 and the RPi4 BT adapter is not the best.
