### ISSUE TITLE
LYWSD03MMC B2.4

### ISSUE THREAD

**Issue by evlo** [pvvx/ATC_MiThermometer#296]
I have one sensor that never I was never, as far as i can remember, read data from, and now I noticed in TelinkMiFlasher it says `Status: Hardware Version: LYWSD03MMC B2.4` - so is there again new, unsupported HW revision?

`Vbat: 2849 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 0, flg: 0x01:r1/t0` - i is outside so that is why the battery is a bit low voltage.
```
1:31:57 PM: Hardware Version: LYWSD03MMC B2.4, Software Version: 4.0, Sensor: SHTC3 (SHTV3)
1:31:57 PM: Custom config HEX string: 55872000002804a97c31803c000000
```

with 4.1 beta it shows reed switch counter (i do not think it does have any reed switches)
```
1:34:03 PM: Hardware Version: LYWSD03MMC B2.4, Software Version: 4.1, Sensor: SHTC3 (SHTV3)
1:34:03 PM: Custom config HEX string: 55876000002804a93131803c000000
Vbat: 2845 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 85, flg: 0x01:r1/t0
```

Update: Hmm, I think it hw probably died, it stopped saving data on december 24th it seems
![image](https://user-images.githubusercontent.com/8813196/219367346-e70f5878-6c07-416e-be2c-7b068c41a25d.png)

**Comment by pvvx** [comment]
> Update: Hmm, I think it hw probably died, it stopped saving data on december 24th it seems

The sensor does not have a time set and is counting from an random date.

> with 4.1 beta it shows reed switch counter (i do not think it does have any reed switches)

But counting of switchings all the same happens? Perhaps the thermometer board is damp and fails.
