### ISSUE TITLE
LYWSD03MMC can be flashed, but I cannot access settings

### ISSUE THREAD

**Issue by irunonayran** [pvvx/ATC_MiThermometer#303]
My thermometer is labeled 2023.01, CMIIT ID: 2019DP8115. After flashing the 4.1 firmware, the device's name changes to ATC, but the device behaves like before flashing. Reinserting the battery does not show the last characters of the MAC. Sending settings like A0 to turn off the emoticon is confirmed in the log, but nothing changes (the options do not appear on the Telink Flash website, but can be written in the send field). Reading the settings does not work either. I work on Linux with Chromium.

**Comment by pvvx** [comment]
What firmware and TelinkMiFlasher.html are you using? [ATC1441](https://github.com/atc1441/ATC_MiThermometer) ?
According to the description, you mixed up the repository.
To work with firmware from this repository, [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) is used.
