### ISSUE TITLE
Major battery drain (faulty unit?)

### ISSUE THREAD

**Issue by mlichvar** [pvvx/ATC_MiThermometer#304]
I have four LYWSD03MMC B2.0, bought at the same time from the same source couple months ago. I flashed the pvvx firmware v3.9. Three are still running fine with the original battery and report about 90% battery left. The fourth one just died with second battery. I thought the original battery was bad, but now I suspect something is wrong with the HW. I measured the consumption and it seems to be around 0.2 mA.

I tried upgrading the firmware to 4.1, but it's still draining. IIRC the only changes I originally made in the configuration was set a PIN, disabled the "comfort" reporting, and set the measurement recording to 0 (disabled). Now I tried "set default" and also switch "lowpower mode", still no luck.

Is there a factory reset or anything else I could try to fix it? Has anyone else seen this issue?

**Comment by erapade** [comment]
I have one out of 10 (with the same configuration and from the same batch) that drains battery.

**Comment by erapade** [comment]
Re-flashing to 4.1 seams to partly have solved my problems. And it might be that I was running on 4.2 beta before, but when checked it was advertising itself as 4.1 but I re-flashed (around 7 PM) anyway and that had a big change

![image](https://user-images.githubusercontent.com/17324892/225522890-b570677c-fa3a-4522-81ce-a5699c7c5940.png)
![image](https://user-images.githubusercontent.com/17324892/225523202-6eb33d0d-7f6d-468a-ac89-012b5098ed12.png)

**Comment by pvvx** [comment]
Check what is displayed in the [Management GPIO_RS (Reed Switch)](https://github.com/pvvx/ATC_MiThermometer#reed-switch-or-button-functions) for the "Switch" and "Counter" options:

![image](https://user-images.githubusercontent.com/12629515/228208254-a3c9c614-0970-43a9-a633-1ad80b6cc351.png)

And what is the specified interval:

![image](https://user-images.githubusercontent.com/12629515/228208290-fc8d8043-00f1-42d6-a2be-2e556f45f380.png)

**Comment by ens4dz** [comment]
I have a question. What is the name of the device used to measure uA in a chart in this great repository? I searched for power, uA, and measure but didn't find any clues.

**Comment by pvvx** [comment]
From ready-made that it is possible to buy - [Power Profiler Kit II](https://www.nordicsemi.com/Products/Development-hardware/Power-Profiler-Kit-2)
If DIY assemble and calibrate yourself  - [PowerProfiler](https://github.com/pvvx/UBIA/tree/master/PowerProfiler)
Or https://github.com/pvvx/PowerProfiler_pcm1802 + INA199An type chips, or or other operational amplifier chips...
And options using an oscilloscope with INA199An type chips..
