### ISSUE TITLE
Can't activate "AdFlags"

### ISSUE THREAD

**Issue by marph91** [pvvx/ATC_MiThermometer#305]
I would like to activate "AdFlags" in order to add my devices to Home Assistant (as mentioned [here](https://github.com/Bluetooth-Devices/bthome-ble/issues/26#issuecomment-1332196521)). However, always when I check the checkbox, it gets unchecked immediately after sending the config. Any idea why it isn't working?

My config:

_Status: Hardware Version: LYWSD03MMC B1.4, Software Version: 3.8_

<img src="https://user-images.githubusercontent.com/33229141/222970927-72ec3639-2fcb-480e-b3e5-76e51a4f8ca3.png" alt="Screenshot_20230305_164724" width="60%"/>

**Comment by pvvx** [comment]
There was an insert of new models of thermometers, and errors arose ...
"AdFlags" fixed.

**Comment by marph91** [comment]
Works now. Thanks for the fast fix!
