### ISSUE TITLE
LYWSD03MMC: Battery level not correct in advertisement ?

### ISSUE THREAD

**Issue by glsf91** [pvvx/ATC_MiThermometer#306]
I have 2 LYWSD03MMC devices with 4.1 on it. I use Bluetooth Advertising Format: Custom format.
The display is showing for both 99 or 98% battery level. But in the advertisement it shows 0x64 (=100%) when I take a look with nRF connect (or another program).
When I connect to the device I see in Battery service/Battery level what is shown on the display (99 or 98%).
Should the advertisement not show the same ?

**Comment by pvvx** [comment]
The display cannot show 100%.

**Comment by glsf91** [comment]
Ok, But it did also show 98% for some minutes on the display but not on the advertisement.
