### ISSUE TITLE
MJWSD05MMC no more lifesign

### ISSUE THREAD

**Issue by Rushmed** [pvvx/ATC_MiThermometer#308]
Hi.

This weekend i succesfuly flashed the BTH_v42.bin (beta) to my MJWSD05MMC.
It was working. After that I pulled out the battery  and layed it to side as I dont need the sensor right now.
Today I wanted to install the final 4.2 but the sensor shows no more sign of life.
Blank display and not disoverable by Flasher.html. Tried several buttonpress combinations.
Tried fresh battery. Checked the hardwarecomponents to be the same as [here](https://pvvx.github.io/MJWSD05MMC/).

What can I do?

**Comment by pvvx** [comment]
[The USB-COM adapter writes the firmware in explorer. Web Windows version.](https://github.com/pvvx/ATC_MiThermometer#the-usb-com-adapter-writes-the-firmware-in-explorer-web-version)
Upload firmware via USB-COM adapter. Connect the TX on the adapter to the ['SWS' on the board](https://pvvx.github.io/MJWSD05MMC/).

**Comment by Rushmed** [comment]
Yess, thanks sir! Sensor is alive.

**Comment by pvvx** [comment]
For MJWSD05MMC, there is a very complex firmware from the original to an alternative version or back.
And in the first versions there were not immediately noticeable errors.
In the current firmware, the OTA part is fixed. But while the beta version, changes and additions are possible until the stable version is released. 
It's good that you managed to restore the thermometer…
