### ISSUE TITLE
Mijia reader app doesn't see thermometer after flashing

### ISSUE THREAD

**Issue by dmig** [pvvx/ATC_MiThermometer#313]
[Mijia Reader ](https://play.google.com/store/apps/details?id=com.freetimeprojects.mijiareader) stopped seeing a thermometer after flashing to custom firmware.

I tried:
- setting _Advertising type_ to _MIJIA_
- playing with _AdFlags_ and _Encrypted beacon_ 
- changing name back to LYWSD03MMC
Nothing helped

Device is LYWSD03MMC, hw 1.4, tried firmware versions 4.1/4.2

**Comment by pvvx** [comment]
Custom firmware does not support MiHome protocol connections.

Mijia Reader: About this app: _This is unofficial application to read and display Xiaomi Mijia Bluetooth Temperature Humidity Sensor data._
Developer contact: mijiareader.info@gmail.com
