### ISSUE TITLE
[Noob question] What's the difference/benefit of using this firmware?

### ISSUE THREAD

**Issue by Draghmar** [pvvx/ATC_MiThermometer#32]
Hi
Sorry for this ignorant, noobish question but what's the benefit of using this firmware vs https://github.com/atc1441/ATC_MiThermometer ? Are there more options to configure? Better battery management? Or something else? :)

**Comment by pvvx** [comment]
Are there more options to configure. 
Better battery management. 
And something else.

**Comment by Draghmar** [comment]
Oh, thanks for the answer. I especially like new bugs! :D
