### ISSUE TITLE
Updated from 2.4. to 4.2 and now Home Assistant no longer receiving updates

### ISSUE THREAD

**Issue by dalanmiller** [pvvx/ATC_MiThermometer#321]
I have upgraded my `LYWSD03MMC` to the latest version of `pvvx` firmware and have stopped seeing temperature and humidity updates. 

Looking at a few other issues, I've checked on `AdFlags` and left the advertising type to the new `BTHome v1`. This differs from my older setup which was using the `All` advertising type. But with these settings, I still am not receiving any updates on my Home Assistant instance. 

The BLE portion of my `configuration.yaml` looks like this:

```
ble_monitor:
```

I've just left everything default and it was working to pick up the updates before. 

Is there anything else I should be doing? I wasn't able to find anything in the docs but I may have missed a setup guide somewhere.

**Comment by pvvx** [comment]
`AdFlags` are required for `Bluetooth` integration to work in `passive scanning` mode.

[ble_monitor](https://github.com/custom-components/ble_monitor) integration works with any settings in the thermometer.

To work at long distances in the `LE long range` mode, an adapter with support for `Bluetooth 5.0` and higher is required. And `Bluetooth` integration.

**Comment by Guirigall** [comment]
Is there any way to get an older firmware? The last one has broken all the BLE communication and as the OP, I get no data from the ATC. I have other ATCs at 3.7 firmware that are working flawlessly.

TIA

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/releases

**Comment by pvvx** [comment]
Support for older versions in TelinkMiFlasher is supported as far as possible...

**Comment by Zebble** [comment]
4.2/4.3 broke HA/ESPHome integration for me as well.  I tried enabling Adflags, but that doesn't seem to make a difference.  I'm using BTHome v1 packet types.

Is there a solution/setting I'm missing?

**Comment by pvvx** [comment]
I haven't seen BTHome support in ESPHome.
And in ESPHome on ESP32 only BT4.0.
ESP32-C3 works extremely unstable in BTHome.

ESP Home previously supported the ATC1441 format.
I don't use ESPHome and I don't recommend it.

**Comment by Zebble** [comment]
Thanks @pvvx,

You are corrent.  There isn't direct BTHome support in ESPHome.  It acts as a bluetooth proxy for HomeAssistant.

3.9 has been working perfectly in this configuration.  Only 4.x seems to break things...

**Comment by pvvx** [comment]
Then why does everything else work, but ESP Home doesn't? :)

**Comment by pvvx** [comment]
Switching formats:
![image](https://user-images.githubusercontent.com/12629515/231604498-f855a4c8-8809-4606-b959-379deba1ab8b.png)

Home Assistant:

ATC1441
![image](https://user-images.githubusercontent.com/12629515/231604510-e4e478a0-8335-4436-846f-12c0fedc7320.png)

PVVX(custom)
![image](https://user-images.githubusercontent.com/12629515/231604561-751262fd-87b0-4aff-beb1-ecfdfad2eec7.png)

MIJIA(MiHome)
![image](https://user-images.githubusercontent.com/12629515/231604605-cda1718f-b93b-4515-9b7d-518f788065a4.png)

BTHome:
![image](https://user-images.githubusercontent.com/12629515/231604654-1c3aab98-739f-49d8-b095-4c3330c5a244.png)

**Comment by pvvx** [comment]
Windows, [python-interface](https://github.com/pvvx/ATC_MiThermometer/tree/master/python-interface)

![image](https://user-images.githubusercontent.com/12629515/231605777-5705a7f6-52c9-4316-bd4f-5ede30a1dd1f.png)

**Comment by pvvx** [comment]
>3.9 has been working perfectly in this configuration. Only 4.x seems to break things...

>[ESPHome Bluetooth Proxy](https://esphome.io/components/bluetooth_proxy.html)

This means that ESP Home does not work with BLE. The BT Home format has not changed from fw version 3.7 to 4.3.

**Comment by 50494554524F** [comment]
> 4.2/4.3 broke HA/ESPHome integration for me as well. I tried enabling Adflags, but that doesn't seem to make a difference. I'm using BTHome v1 packet types.
> 
> Is there a solution/setting I'm missing?
> 
> FYI, it worked with 3.9 and have gone back to 3.9.

i tested v4.2 + bthome + esp32 bluetooth proxy and it works...

**Comment by pvvx** [comment]
> i tested v4.2 + bthome + esp32 bluetooth proxy and it works...

ESPHome does not work with Bluetooth 5.0 from 2016.
