### ISSUE TITLE
Not a bug- a small problem and help needed.

### ISSUE THREAD

**Issue by KeinPlandavonviel** [pvvx/ATC_MiThermometer#323]
I hope it's ok to post this here, didn't know where else is an active community.
Hoping to achieve a slightly higher range on one of my hygrometers (LYWSD03MMC) I increased the transmit power by the maximum possible +3dB and switched LongRange without thinking about the BT 5.0 requirement.
This came to me after the "tap" on transmit. :o)

Unfortunately, I can not find the sensor now, even with my Oneplus 7T Pro (Lineage 20.0 / Edge / experimental mode on), although the phone should be able to BT 5.0.

Does anyone have a tip on how I can save the sensor? Is there any way for a reset? 
What happens with installed PVVX hardware and a hard reset?
Do I first have to switch on BT 5 on the smartphone under Lineage? Root available.

Help would be nice.

EDIT:

After taking out the battery and new boot the LR mode is off and I could connect directly!
Is this a failsafe? If yes - thank you very much!

**Comment by pvvx** [comment]
To achieve the same range in the "Legacy" mode, compared to the "LE long Range" mode, an increase in RF TX recoil from +7 dBm is required. This is not available with CR2032.
When compared with Bluetooth 4.0, it is required to increase the power of the transmitter several times more...
When switching to "LE Long Range", the transmission time increases by 8 times, but the current from the battery remains the same (6..7mA at +0 dBm). 
To coordinate the total consumption, set the BLE advertising interval in the range of 5 seconds or more.

Для достижения той же дальности в режиме "Legacy", по сравнению с режимом "LE long Range", требуется увеличение отдачи RF TX с +7 дБм. Это недоступно с CR2032.
По сравнению с Bluetooth 4.0 требуется ещё увеличить мощность передатчика в несколько раз...
При переключении на "LE Long Range" время передачи возрастает в 8 раз, но ток от батареи остается прежним (6..7мА при +0 дБм). 
Чтобы скоординировать общее потребление, установите интервал BLE рекламы в диапазоне от 5 более секунд.

---

Disabling "LE Long Range" is performed in nRFConnect as specified in README.md .

Отключение "LE Long Range" выполняется в nRFConnect, как указано в README.md .

**Comment by pvvx** [comment]
The package for BT4.2 is very limited in size. As a result, all variables are passed in turn. The formats used require at least 3 advertising BLE events.

**Comment by pvvx** [comment]
Each measurement is accompanied by multiple calculations and preparations of variables for transmission.  These actions require energy for the processor to work.
The temperature and humidity sensor also increases consumption during the measurement. And for STHV3, the measurement time is more than 11 ms and it must be accompanied by the actions of the CPU - to awaken the sensor from sleep, give the measurement command, fall asleep while waiting for the end of the measurement, wake up the CPU, read the readings, give the sensor the command to fall asleep. All this is energy-consuming and comparable to the activity of RF TX when transmitting BLE advertising.
