### ISSUE TITLE
Looking for bluetooth 5.0+ usb adapter recommendations

### ISSUE THREAD

**Issue by delet-this** [pvvx/ATC_MiThermometer#325]
Are there any specific, preferably cheap bt 5.0+ usb dongles you would recommend to use with this firmware + LYWSD03MMC? Or should I just choose something from here https://www.home-assistant.io/integrations/bluetooth#realtek-rtl8761bu-adapters

Thanks!

**Comment by pvvx** [comment]
There are many RTL8761BU adapters. The speaker in RTL8761BU is loaded by the system, and it makes no sense to look at the label on the adapter. The downloadable FW in RTL8761BU has long supported Bluetooth 5.1.

**Comment by delet-this** [comment]
Thank you! I think any RTL8761BU adapter should fit my needs for now.

**Comment by pvvx** [comment]
Orange Pi 3 TG, Pi 5, ... have already been adjusted and are working with the `LE Long Range`.
