### ISSUE TITLE
LCD boot info?

### ISSUE THREAD

**Issue by tablatronix** [pvvx/ATC_MiThermometer#326]
How do I get the boot info back?
My older devices show ATC and the last mac octet ID on the lcd on power up

I am not seeing this now..

**Comment by pvvx** [comment]
https://github.com/atc1441/ATC_MiThermometer

**Comment by tablatronix** [comment]
Are you saying you removed this, or was this added after forking? I mean its a good feature, I have to write addresses on the back in sharpie...

**Comment by pvvx** [comment]
For this function, it is necessary to pick out the battery and break the cover fastenings.
The device name and MAC are changed programmatically.
Identification is performed when connecting to the device and is displayed by the "connections" icon.

**Comment by tablatronix** [comment]
failure of clocks, you mean timestamps? I dont use logging. But I do need to know the id of the device I just powered up, doesn't really harm anything.

Popping the battery on a mijia lyd is not that big a deal, maybe on others.

**Comment by pvvx** [comment]
The [fw variant from ATC1441](https://github.com/atc1441/ATC_MiThermometer) has the necessary function.

**Comment by tablatronix** [comment]
Yours is better 😄
