### ISSUE TITLE
MCCGQ02HL support?

### ISSUE THREAD

**Issue by miksumin** [pvvx/ATC_MiThermometer#330]
Добрый день,
Подскажите, возможно ли добавить поддержку MCCGQ02HL (Xiaomi Mijia Window Door Sensor 2)?

**Comment by pvvx** [comment]
Я не знаю какой там чип.
И каков в этом смысл? Датчик MCCGQ02HL достаточно дорогой и нераспространённый. Он вроде и так работает нормально?

**Comment by miksumin** [comment]
В России датчик стоит 700 руб, что на мой взгляд совсем недорого по сравнению с другими датчиками.
Обратился к Вам, потому что не нашел как его можно прочитать без использования Mi Home и Bind Key.

**Comment by pvvx** [comment]
А что пишет [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) на MCCGQ02HL?

**Comment by miksumin** [comment]
Пишет "Not found Telink OTA service!" Хотя обновление прошивки по воздуху в Mi Home работает.
Описания и фото внутренностей в Инете не нашел, но могу свой датчик вскрыть и сфоткать, если это поможет.

**Comment by miksumin** [comment]
После выполнения Pairing через Mi Home он теперь шлет вот такие данные, судя по всему зашифрованные:
02 01 06
19 16 [95FE] 58588B0986 [4B2563ECAAE4] 83A0F1FB000000D0FF22E7
Bind Key для него я вытащил, осталось сделать дешифровку

**Comment by miksumin** [comment]
![20230412_112211](https://user-images.githubusercontent.com/63466871/231398576-058435c9-0132-4662-b730-84bcbff77005.jpg)
![20230412_112049](https://user-images.githubusercontent.com/63466871/231398593-a1a700f9-7a2c-44ef-810d-22b9f6c53036.jpg)

**Comment by miksumin** [comment]
Теперь у вас есть информация о чипе. Подскажите, есть возможность сделать поддержку такого типа датчиков?

**Comment by pvvx** [comment]
> Bind Key для него я вытащил, осталось сделать дешифровку

Тут есть дешифровка для данного датчика
[ble_monitor](https://github.com/custom-components/ble_monitor/blob/master/custom_components/ble_monitor/ble_parser/xiaomi.py)

> Подскажите, есть возможность сделать поддержку такого типа датчиков?

Данный репозиторий связан только с датчиками температуры и влажности на Telink чипах типа TLSR825x.
А у вас чип от Silabs [EFR32BG21](https://www.silabs.com/wireless/bluetooth/efr32bg21-series-2-socs).
Создавать свою прошивку для данного чипа я точно не буду, т.к. не вижу в этом смысла и у меня нет, и не предвидится, таких датчиков. Для прошивки EFR32BG21 по OTA требуется крипто подпись и никто данными хаками не занимается.

**Comment by miksumin** [comment]
Ясно, спасибо.
