### ISSUE TITLE
cgdk2-2

### ISSUE THREAD

**Issue by FreelandA** [pvvx/ATC_MiThermometer#336]
I bought what I thought was a new batch of CGDK2s, but turned out to be a new revision, the CGDK2-2. I can't get them to connect to the Telink web app. Are they compatible?

**Comment by pvvx** [comment]
You have provided very little information to answer. Several new CGDK2 have appeared for a long time. All of them are supported.

**Comment by FreelandA** [comment]
I just checked the listing and they added a not that it doesn't support bluetooth. 
https://www.aliexpress.us/item/3256801989523547.html?spm=a2g0o.order_list.order_list_main.22.d6d518027goeyi&gatewayAdapt=glo2usa

**Comment by pvvx** [comment]
This is "Qingping Temp & RH Monitor Lite E".
And this is the old version.
[CGDK2-2](https://pvvx.github.io/CGDK2/CGDK2-2)
