### ISSUE TITLE
What is the max Measure Interval value?

### ISSUE THREAD

**Issue by nadnerb33** [pvvx/ATC_MiThermometer#35]
Ideally I only want a reading every 10 minutes to save battery drain from frequent measurements, but also to stop my DB and graphs getting clogged with data.

So I need a measure interval of 240 x 2500ms (default adv interval) = 10 mins

It seems you can only enter 2 digits, so I tried 99 and saved config, but it always resets to 10x
I've also tried 20x and 30x, but it resets. 

Am I doing something wrong? I set the value and then click "Send Config" and the log output says it was successful.

edit: I'm using the OTA flasher and the v1.9 fw

edit2: ok, I see in [app.c](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/app.c) that values over 10 get set to 10. 
Why is that, is there a limit elsewhere?  
I tried to increase advertising interval, but I lost connection, so the actual maximum is 25~30 seconds (or 100 seconds if I increase adv int and accept I won't be able to connect again)

**Comment by pvvx** [comment]
> Ideally I only want a reading every 10 minutes to save battery drain from frequent measurements

Increasing the measurement interval will not save energy. Percentage shares.

https://github.com/pvvx/ATC_MiThermometer/issues/23#issuecomment-766898945

**Comment by pvvx** [comment]
> but also to stop my DB and graphs getting clogged with data.

Turn on the averaging of results in your database and save every 10 minutes. This will give precision accuracy.

**Comment by pvvx** [comment]
For intervals longer than N minute, a different program is required. Incompatible with current firmware.
The device sleeps for N minutes and is activated, measures and issues several beacons. And a new cycle.

**Comment by nadnerb33** [comment]
thanks, I'll set it to the max and then filter on the DB side.
