### ISSUE TITLE
About Signal Strength and Distance

### ISSUE THREAD

**Issue by manelrodero** [pvvx/ATC_MiThermometer#356]
**What is needed for the Signal Strength diagnostic entity to appear on a Xiaomi LYWSD03MMC?**

I'm testing a couple of them. The first one I linked to Home Assistant using Bluetooth/Xiaomi-BLE integration. I got the values of all the entities after waiting for about 12 hours (I explained it here https://github.com/home-assistant/core/issues/82751#issuecomment-1605296459). Then I changed the firmware to PVVX 4.3, with advertisement Mijia and everything is still working fine.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/26098260/38b467fd-44f9-4156-a72f-8b440186a622)

The second I directly changed the firmware and put the same configuration as the first. That's more than 24 hours ago and I still haven't received signal values.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/26098260/f5ccd3aa-f772-482d-8422-a2c08232acfc)

It is also true that I have had it 180cm from the Raspberry Pi 4, on the other side of the wall. Now I have left it 60cm from it to see if it will be added in a few hours.

It is probable that one day I will change the Raspberry Pi 4 for a Mini PC with a better Bluetooth but, for now, **what parameters would have to be modified in the sensors so that the signal arrives depending on the distance at which they are placed?** (inside the house, on the balcony, in the garden, etc.)

Thank you.

**Comment by pvvx** [comment]
The readings of the "Signal level" directly depend on the IE adapter and its driver.
On the USB-BT I use, these readings appear immediately.
