### ISSUE TITLE
New chart style in GraphMemo?

### ISSUE THREAD

**Issue by lukaszswitaj** [pvvx/ATC_MiThermometer#357]
Hi,

There is a screenshot of a pretty nice set of charts in Readme.md:

![chart](https://camo.githubusercontent.com/d1e173976a2c68afd7611ec41949e08bc7652da0f5a684e4e4ac91549ae65565/68747470733a2f2f707676782e6769746875622e696f2f4154435f4d69546865726d6f6d657465722f696d672f576561746865722e676966)

Is this some new way to visualize downloaded sensor data directly in the browser? The graphs drawn here look completely different: https://pvvx.github.io/ATC_MiThermometer/GraphMemo.html

**Comment by lukaszswitaj** [comment]
Forgive me, this illustration is just below the link to [GraphMemo.html](https://pvvx.github.io/ATC_MiThermometer/GraphMemo.html). It's very confusing.

By the way, maybe it's worth posting an instruction on how to convert timestamp from generated CSV files to date-time format in Calc and Excel.

**Comment by pvvx** [comment]
The csv file describes the conversion formula in the first row of the first column:
`Time-Data=(A2/86400)+25569`

**Comment by evlo** [comment]
I don't understand the excel? formula or in general _time-data?_ what does that actually mean

![image](https://github.com/pvvx/ATC_MiThermometer/assets/8813196/9e002e97-0716-4233-b059-ebfc0d515c35)

**Comment by evlo** [comment]
I do not understand

this is what I get on the device so date and time is correct

![image_2023-09-27_13-44-37](https://github.com/pvvx/ATC_MiThermometer/assets/8813196/6c1605fe-ab07-46ce-b5de-34face2227fd)

these are results in excel + formula I'm using

![image](https://github.com/pvvx/ATC_MiThermometer/assets/8813196/74ecc339-a0cd-4ab2-875f-23f7e69932f2)

`rrrr-mm-dd h:mm;@` is cell froamt, but I do have czech localisation of excel, sadly

**Comment by pvvx** [comment]
After the firmware, you need to set the clock in the thermometer - "Set time".
[Instability of the time count on the thermometer.](https://github.com/pvvx/ATC_MiThermometer/issues/56)
There are already several applications for synchronizing the time on the thermometer.
Example:
**ESPHome**: [synchronize the time once a day](https://esphome.io/components/display/pvvx_mithermometer.html#only-synchronize-the-time-once-a-day)
