### ISSUE TITLE
Flashing LYWSD0MMC flashed with old ATC firmware ?

### ISSUE THREAD

**Issue by francisp2** [pvvx/ATC_MiThermometer#365]
Is it possible ? The TelinkMiFlasher.html throws errors trying to connect.
TypeError: device.watchAdvertisements is not a function
and
TypeError: getDevVersion(...) then is not a function

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/362#issuecomment-1637068693
