### ISSUE TITLE
Slow sensor updates, cant figure out

### ISSUE THREAD

**Issue by minermartijn** [pvvx/ATC_MiThermometer#367]
Soo, first of all, your firmware is awesome. And i've upgraded 2 of my ATC LYWSD03MMC to use yours.
And it all works, only thing that i cant seem to figure out is that sometimes it updates within a minute on HA.
And sometimes it takes over 15 min, sometimes it becomes unavailable..

I got one very close to my bluetooth adapter, and one a bit further away.
If you need more info i will ofcourse share it, but im at work and cant access the bluetooth firmware side of things right now.

I've set it to bthome, becuase i couldnt get the others to work and didnt want to keep using the xiaomi app.

**Comment by pvvx** [comment]
The update time from the state of the original Xiaomi version does not depend on the new firmware code. This time is normalized in accordance with the original official version of the program and the quality of your device transmitting the update code.

**Comment by minermartijn** [comment]
I think i explained wrong.
You are talking about updating the firmware right?

But i mean that it sometimes takes 10 minutes to update the temperature or humidity. I wish i would update like every 5 seconds and cant seem to find out how.

**Comment by pvvx** [comment]
It depends on the BT adapter and the internal settings in HA.

**Comment by minermartijn** [comment]
Then it must be my adapter. I uae the Rolio bluetooth 5.1 adapter.

And i have my settings on 2500ms i think. Not at home right now.

![Screenshot_20230822_083047_Home Assistant.jpg](https://github.com/pvvx/ATC_MiThermometer/assets/51987758/b4e2a73d-06b4-43b2-927c-835aa8cc1987)

As you can see on my screenshot it sometimes takes very long to update

**Comment by mmib** [comment]
have the same issue. Set interval to 8000ms and measure interval to 35 to receive updates each 4-5 minutes. At the beginning it worked but then stop (look at this gap at night)
![photo_2023-08-24_10-37-26](https://github.com/pvvx/ATC_MiThermometer/assets/6117591/d5856631-b8a6-4904-856f-5269a09d7c9b)

**Comment by pvvx** [comment]
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/e5b2a053-ccdc-406e-9162-68769a9e97f5)

Step 60 seconds:

![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/27f70df9-3055-456d-aab3-53510130fa16)

Part of the devices, reception on one USB-BT adapter, only BLE thermometers:

![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/e19d1d57-e6f6-44be-93c3-908e5c9e163a)

![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/ad654509-70a4-4717-a2ae-87f604906106)

**Comment by minermartijn** [comment]
Aaah, you are using a different bluetooth integration, im going to try that one now, saw i could install it using hasc.

**Comment by minermartijn** [comment]
Oke, quick update! 
The other integration made all the difference for me, its updating atleast within a minutes now.
And works so much better!!! Thanks PVVX! YOU THE MAN!

![NewBLEIntegration](https://github.com/pvvx/ATC_MiThermometer/assets/51987758/745985fa-d481-47b9-aa58-b30cf1174bf5)

**Comment by minermartijn** [comment]
This issue can be closed, atleast for me. Thanks again pvvx!! :)

**Comment by pvvx** [comment]
I use two of BT integrations ("[Bluetoth](https://www.home-assistant.io/integrations/bluetooth/)" and "[Passive BLE monuitor](https://github.com/custom-components/ble_monitor)") and two USB-BT adapters.
