### ISSUE TITLE
Missing digit on display when temperatur is -0.9

### ISSUE THREAD

**Issue by MrGoodbody** [pvvx/ATC_MiThermometer#37]
Hi,
first thanks alot for your pretty nice work in this repository!
When the temperatur of -0.9 should be displayed, the lcd shows "- .9" 
I think there is an error in file https://github.com/pvvx/ATC_MiThermometer/blob/master/src/lcd.c line 113
`		if(number < 9) display_buff[4] |= 0xF5; // "0"`
i think it should be
`		if(number <= 9) display_buff[4] |= 0xF5; // "0"`
haven't tested it.
Thanks!

**Comment by pvvx** [comment]
Thanks! Ver 2.0 patch
