### ISSUE TITLE
Cant connect to LYWSD03MMC w. Telink after setting Advertisement to 5000ms

### ISSUE THREAD

**Issue by g6094199** [pvvx/ATC_MiThermometer#371]
the unit gests scanned

![grafik](https://github.com/pvvx/ATC_MiThermometer/assets/37833326/f37889aa-d39c-40d7-a3e2-12dde619866a)

but the connection is always unsuccessfull. it stops reconnecting after 1st try.

![grafik](https://github.com/pvvx/ATC_MiThermometer/assets/37833326/2ccee304-d016-460a-ab9d-00d8040b2e50)

Ubuntu 23.04
Chromium Version 116.0.5845.110
or
 Microsoft Edge Version 102.0.1245.7

**Comment by pvvx** [comment]
These are problems in the Linux kernel.
Linux does not have full support for BLE standards. Bluetooth version 4.2, released in 2016, is not yet fully supported.
It is necessary to patch the kernel and use additional commands in the API.

**Comment by pvvx** [comment]
Change the settings in Bluez to default values for the Bluetooth standard in /etc/bluetooth/main.conf.
