### ISSUE TITLE
Both button in MJWSD05MMC 

### ISSUE THREAD

**Issue by AGRO666** [pvvx/ATC_MiThermometer#373]
Are there any plans to create support in MJWSD05MMC for using both buttons?

**Comment by pvvx** [comment]
The upper button enables connection by short pressing, and switching screen types by long pressing.
You can use the button to select which values will be displayed in the main line.


The bottom button works as a "Switch" in Home Assistant.
Selecting the function of the second button in the "Reed Switch" menu TelinkMiFlasher.html.

See screen on https://github.com/pvvx/ATC_MiThermometer/issues/322#issuecomment-1485002996
