### ISSUE TITLE
[Need help] reed switch is triggered in Bluetooth Connection Mode LYWSD03

### ISSUE THREAD

**Issue by AGRO666** [pvvx/ATC_MiThermometer#375]
How can I get a signal when the reed switch is triggered in Bluetooth Connection Mode?

**Comment by pvvx** [comment]
There are problems with the SDK. When the connection is active, an interrupt from GPIO causes failures in the closed libraries of the BLE part of the SDK...

You can get the status of the reed switch bits when the "Start notifying about measures in connection mode" function is enabled (code "33ff" or by enabling automatic transmission in the TelinkMiFlasher menu - when connected, this is equivalent to executing the "33ff" command). But the survey is performed only at the time of measurement - the measurement period.
It is also possible to get the data of the flag bits using the command "Set TRG output pin" (code "45" without a parameter).
