### ISSUE TITLE
LYWSD03MMC DisplayDisable

### ISSUE THREAD

**Issue by RustyMan22** [pvvx/ATC_MiThermometer#383]
I have 1st version of 
[Xiaomi Mijia (LYWSD03MMC)]

Can i set Display to Off or just blank?
I was thinking of adding small push button to enable Display just for "push moment" but device use calculator rubber string to connect data pins. 
I read that firmware has relay control via reset pin.
Can i use this pin to tell device to enable Display if push button is pressed?

Thank you in advance

**Comment by pvvx** [comment]
1. The display control chip requires reinitialization after disconnection. 
2. Not all LCD driver chips have full documentation.
3. Displaying an empty display does not reduce consumption.

The current implementation, when switching the display chip to sleep mode, uses a full system reboot. To reduce power consumption when the display is on/off, it is recommended to remove and insert the battery (see 1, 2).
