### ISSUE TITLE
Reading fluctuations

### ISSUE THREAD

**Issue by melwinek** [pvvx/ATC_MiThermometer#398]
Thermometers with hardware version B1.4 have reading fluctuations.  This is not the case in B1.7.  Is this typical for this version?  Can something be done about it?

Normal:
![Screenshot_20231029-070921_Pixel Launcher](https://github.com/pvvx/ATC_MiThermometer/assets/10649327/88dd11d6-0fdd-4f3c-b546-8f15c0ee7818)

Fluctuations:
![Screenshot_20231029-070944_Pixel Launcher](https://github.com/pvvx/ATC_MiThermometer/assets/10649327/4f0422da-8ffc-4286-aa73-7df5fe4b8dc2)

**Comment by melwinek** [comment]
Can be closed.  Disabling "Sensor in Low Power mode" solves the problem

**Comment by pvvx** [comment]
B1.4 uses a different sensor (SHTC3).
Compared to the new versions (SHT4x), this sensor has a higher consumption and a faster response to changes in the measured parameters of the medium.
In low power mode, SHTC3 gives inaccurate readings. And for SHT4x, the polling algorithm changes, which does not affect accuracy.
