### ISSUE TITLE
Display stays empty after flashing ATC_Thermometer20p.bin

### ISSUE THREAD

**Issue by hmeyer** [pvvx/ATC_MiThermometer#40]
The title says it all. I flashed ATC_Thermometer20p.bin onto a new Device and the Display stays empty.
The device is up and running and sending beacons, but the display is empty.
Am I missing some config setting?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/24#issuecomment-766761834

**Comment by hmeyer** [comment]
Thanks!
