### ISSUE TITLE
MJWSD05MMC ESPHome

### ISSUE THREAD

**Issue by V-VoRteX-V** [pvvx/ATC_MiThermometer#400]
How to display temperature from HA sensor? With LYWSD03MMC everything is fine using commands it.print_bignum or  it.print_smallnum https://esphome.io/components/display/pvvx_mithermometer.html 
But MJWSD05MMC works strangely, it displays incorrectly

**Comment by pvvx** [comment]
MJWSD05MMC uses a different format and displays only 1 number.
 number: -999.50 .19999.50, in 0.01: -99950..1999950
```
 *  -999	(-9.99)	[ -999][ -9.99]
 *   -99	(-0.99)	[ -99 ][ -0.99]
 *    -9	(-0.09)	[  -9 ][ -0.09]
 *     9	(0.09)	[   9 ][  0.09]
 *    99	(0.09)	[  99 ][  0.99]
 *   999	(9.99)	[ 999 ][  9.99]
 *  9999	(99.99)	[ 9999][ 99.99]
 * 19999	(199.99)[19999][199.99] 
```

https://esphome.io/components/display/pvvx_mithermometer.html - this only works for Xiaomi LYWSD03MMC

**Comment by V-VoRteX-V** [comment]
Thanks for the number format, I'll convert the values. But then how to correctly transfer the number to MJWSD05MMC from Home Assistant?
