### ISSUE TITLE
Bricked after flashing z03mmc.bin [HELP]

### ISSUE THREAD

**Issue by QUINRY** [pvvx/ATC_MiThermometer#403]
Hi,

İ'm flashed z03mmc.bin for zigbee support for my LYWSD03MMC.

After flash, device shows temp. and humidity but not BLE is not working.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/136974131/9031460b-1110-4bd7-843f-48653eea3ca2)

After a few seconds, the screen stays like this and no ble appears again.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/136974131/aa06221e-6b78-4377-a5a3-929b6886a7b4)

How can i fix this?

**Comment by QUINRY** [comment]
@pvvx

**Comment by pvvx** [comment]
Without registration in the Zigbee network, the thermometer does not work. Registration of the thermometer in the Zigbee network is carried out by closing the “reset” contacts with “gnd” for 3 seconds or when turning on the power after flashing. To save power, the registration time is limited by turning off the thermometer after 45 seconds.

**Comment by QUINRY** [comment]
> Without registration in the Zigbee network, the thermometer does not work. Registration of the thermometer in the Zigbee network is carried out by closing the “reset” contacts with “gnd” for 3 seconds or when turning on the power after flashing. To save power, the registration time is limited by turning off the thermometer after 45 seconds.
> 
> https://github.com/pvvx/z03mmc

Can't I flash any other firmware anymore?

**Comment by pvvx** [comment]
Use Zigbee OTA.

**Comment by QUINRY** [comment]
> Zigbee OTA

Where can I find it and how can I do it?

**Comment by pvvx** [comment]
You have flashed a program for the thermometer to work on the Zigbee network.
The ZigBee standard has "ZigBee OTA" in its specification.

**Comment by wildekek** [comment]
Your best bet is using this: https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files
