### ISSUE TITLE
Incorrect Fahrenheit calculation in ≥4.5

### ISSUE THREAD

**Issue by thedanbob** [pvvx/ATC_MiThermometer#406]
After updating to v4.5 I noticed that the calculation for °F is incorrect. For example, one sensor I have is currently reporting 22.16°C (71.89°F) but it is displaying 36.0°F. Same behavior in v4.6 but v4.4 is correct.

I'm guessing the bug was introduced here but I'm not certain: https://github.com/pvvx/ATC_MiThermometer/commit/9d8caf7e35b05e3a8564b3ebf2e5f7e99682509b#diff-6184566596a46e0fc3c56159deebe6cb070d3a65dd5ef3ba7342d0945c498677

Edit: figured it out and made a PR: https://github.com/pvvx/ATC_MiThermometer/pull/407

**Comment by cmptrphreak** [comment]
I encountered the same on 4.5. its 363F in my office now.

**Comment by Jefrysuko** [comment]
Same here.  22.45°C is converting to 361°F

**Comment by thedanbob** [comment]
Confirming this is fixed in the updated v4.6.
