### ISSUE TITLE
Send version string

### ISSUE THREAD

**Issue by andreas-bulling** [pvvx/ATC_MiThermometer#408]
With many sensors distributed across the house, it'd be super useful if the thermometer also sent the version string of the firmware so that it can be nicely seen in HomeAssistant for example.

**Comment by pvvx** [comment]
This standard feature for BLE can be implemented in any device without increasing the battery consumption of the thermometer for the constant additional transmission of one-time information.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/58e669f2-f0ec-4065-a196-06a113ec26aa)

**Comment by tmugan** [comment]
This sounds like a good idea to me. 
https://community.home-assistant.io/t/make-ble-softwarerevisionstring-available/640675?u=tmugan
