### ISSUE TITLE
TypeError: getDevVersion(...).then is not a function

### ISSUE THREAD

**Issue by casperghst42** [pvvx/ATC_MiThermometer#409]
Hi,

I'm trying to update my BLE devices (Xiaomi Mijia (LYWSD03MMC)) which are running an old version of the ATC firmware.

When I connect to the device I get this:

2:22:16 PM: Searching for devices
2:22:20 PM: Connecting to: ATC
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Reconnect 1 from 5
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Reconnect 2 from 5
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Reconnect 3 from 5
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Reconnect 4 from 5
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Reconnect 5 from 5
2:22:26 PM: TypeError: getDevVersion(...).then is not a function
2:22:26 PM: Something went wrong, too many reconnects

HW: MacBook Air M2
OS: MacOS 14.1
Browser: Chrome 119.0.6045.123 

How can I resolve this?

Cheers.

**Comment by pvvx** [comment]
https://atc1441.github.io/TelinkFlasher.html
