### ISSUE TITLE
(Zigbee) Which version should I install ?

### ISSUE THREAD

**Issue by Toniob** [pvvx/ATC_MiThermometer#412]
Hi,

First, thank you for your amazing work. I’ve tried the Zigbee version and it seems to work fine. But I’m a little confused. Should I install your version, or this one : https://github.com/devbis/z03mmc . Do you plan on merging the 2 projects and working together, or will it be 2 separate projects ?

Right now, with your version, everything is ok in zigbee2mqtt, but it seems the ota updates don’t work because they are made for the devbis versions. This is quite confusing.

**Comment by pvvx** [comment]
The Zigbee project has expanded to several [IoT devices using the TLSR825x chip](https://github.com/pvvx/ZigbeeTLc).
But it is still in beta testing.
While the firmware options are in beta testing, I will not post them in the [general lists of automatic updates](https://github.com/Koenkk/zigbee-OTA) for all Zigbee devices. Only manual updating is possible.
