### ISSUE TITLE
LYWSD03MMC Version: 2.1.1_0159 is temporarily not supported

### ISSUE THREAD

**Issue by ArmenVanlasso** [pvvx/ATC_MiThermometer#413]
Please repair this.
![Zrzut ekranu 2023-11-16 221508](https://github.com/pvvx/ATC_MiThermometer/assets/81431935/34f8343f-da69-44ff-b077-00040553479f)

**Comment by ilgrank** [comment]
Before opening an issue you should check if there's already a prior one:
[https://github.com/pvvx/ATC_MiThermometer/issues/378](https://github.com/pvvx/ATC_MiThermometer/issues/378)
Take your time to read thru it, and you will have your answer.
