### ISSUE TITLE
Strange repeated temperature readings in v4.5

### ISSUE THREAD

**Issue by chatziko** [pvvx/ATC_MiThermometer#418]
Hello, I just upgraded two sensors to v4.5 (from v4.3 if I recall correctly) and started seeing strange temperature readings in both of them.

Below you can see the difference before and after the upgrade (which happened around 10:00 yesterday):

![Screenshot from 2023-11-24 11-40-55](https://github.com/pvvx/ATC_MiThermometer/assets/362089/a56b6d72-e4a1-467c-a5d5-3b4000f2e953)

Zooming in around 21:00 (after the upgrade) we see that the sensor reports a strange value of 19.67 once per minute or so, independentely from whether the actual value was below or above 19.67:

![Screenshot from 2023-11-24 11-51-35](https://github.com/pvvx/ATC_MiThermometer/assets/362089/2d40480c-afaa-4966-9f9c-716d0e8bb647)

The second sensor has exactly the same behaviour, but its frequently reported value is 20.52. I tried moving it to a colder location to see that happens, and the 20.52 is still reported, although much less frequently, as can be seen below.

![Screenshot from 2023-11-24 11-59-08](https://github.com/pvvx/ATC_MiThermometer/assets/362089/678f9cc6-6809-4192-9a94-90bad3590030)

Any idea what could be the cause of this?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/405

**Comment by chatziko** [comment]
Oh, thanks! I would have sweared I checked the issues before posting, but I guessed I looked only at the open ones :smile:

**Comment by pvvx** [comment]
The reason is not the thermometer or your actions.
The reason is Bluez and the Linux kernel.
