### ISSUE TITLE
QUESTION: Does MJWSD05MMC support both MiHome app and XiaomiGateway 3 in HA?

### ISSUE THREAD

**Issue by JonathanKang** [pvvx/ATC_MiThermometer#425]
Does MJWSD05MMC support both MiHome app and XiaomiGateway 3 in HA with this custom firmware, as MJWSD03MMC does?

**Comment by pvvx** [comment]
The Mi Home user agreement prohibits such actions. You cannot use Xiaomi Clouds and their software without violating the user agreement.

**Comment by JonathanKang** [comment]
> Publish the remaining parts in open sources to implement compatibility with MiHome - then it will be possible to add them to alternative firmware without breaking laws.

I'm using your custom firmware in my LYWSD03MMC thermometer, both in MiHome app and XiaomiGateway 3 in HA. It works as expected. Does this also violates the user agreement? Can MJWSD05MMC work similarly with LYWSD03MMC? I tried this earlier today, but it doesn't seem to work.

**Comment by pvvx** [comment]
> Does this also violates the user agreement? 

Have you read it? The text appears when the device is connected and in the menu. :)

**Comment by JonathanKang** [comment]
> Have you read it? The text appears when the device is connected and in the menu. :)

Turns out it does violate the user agreement. 

Well, let's put the user agreement aside for now, is it possible to work work MJWSD05MMC with 'Xiaomi Gateway 3'?

**Comment by pvvx** [comment]
> Well, let's put the user agreement aside for now, is it possible to work work MJWSD05MMC with 'Xiaomi Gateway 3'?

Where should I put it?

MJWSD05MMC seems to be made for the Chinese domestic market.
Register there.

**Comment by JonathanKang** [comment]
Nice. Thanks. I'll stick with the original firmware.

**Comment by pvvx** [comment]
Oh, another one ran away and didn’t give everyone instructions on how to attach the thermometer to MiHome and who they could then link to :)
