### ISSUE TITLE
Name of the device not show in Home Assistant

### ISSUE THREAD

**Issue by Misiu** [pvvx/ATC_MiThermometer#426]
First of all, thank you for the project, I've just flashed my first LYWSD03MMC, the process was so easy and well-described.
After uploading firmware 4.5 and setting the advertising type to BTHome v2 (and saving config) the device showed up in Home Assistant as:

![ha_discovery](https://github.com/pvvx/ATC_MiThermometer/assets/1741838/d80baa19-2c3d-4fdd-8c63-4ca8432e97f8)

I've set the device name and that name is shown when I try to connect to a Bluetooth device from my browser and when I use `Get device Name`, but it isn't used in Home Assistant.

![image](https://github.com/pvvx/ATC_MiThermometer/assets/1741838/e0bac6cb-cb12-417f-a326-310ebff7124f)

Before I start an issue in the Home Assistant repo I'd like to be sure that the `Local Name` is sent in the advertising payload (according to the format: https://bthome.io/format/)

I'm probably not the only one who plans to use more than one device, so adding a custom name and seeing that name in HA would be very helpful.

**Comment by pvvx** [comment]
Your image displays the name it received when you scanned it.

The [BTHome format](https://bthome.io/format/) does not contain the device name. There are standard Bluetooth identifiers (0x09 - Complete local name) for this in BT/BLE.

**Comment by Misiu** [comment]
@pvvx thank you for your reply.
If I understand correctly we can't set a complete local name based on the device name, is this right?
I'm not sure what and where should be changed to get the correct behavior - the device name should be shown in HA in discovered devices.
I use Shelly as BT Proxy, it has the passive scan selected. I've changed it to active, but this didn't change.

If everything is correct on your site (I just wanted to be sure) I'll create an issue in HA Repo.
To be 100% sure, the device name we can set using Flasher isn't related to the advertising type and is a standard BT feature?

**Comment by pvvx** [comment]
Yes. Both in the BT advertising message and in the attributes.

**Comment by pvvx** [comment]
There is a lot of useful stuff missing from Home Assistant.
I can't move this matter forward alone. The only responses I receive are references to using Bluez or other APIs, which prevent them from working. And following the chain where they direct you, you will get to the Linux kernel. But it has its own cockroaches and there has been no full support for BT4.2 since 2016.

**Comment by Misiu** [comment]
@pvvx I've created a new issue, let's wait for the devs' response.
The device name is set here: https://github.com/Bluetooth-Devices/bthome-ble/blob/4cb68589dabe995df04bb6abf2cbc9a1e62d9687/src/bthome_ble/parser.py#L266
I'll try to set up the environment and debug it.

Sadly I'm not sure how this works when using ESPHome or a Shelly based proxy.

**Comment by Misiu** [comment]
I've tried that.
I've flashed the device, set the name, restarted HA and then checked for discovered devices.

Do you have BT on the machine running HA or are you using BT Proxy?

**Comment by Misiu** [comment]
> I'm running Ubuntu and HA in Docker. I'm using the built-in BT.

That might be the reason.
I'm running HAOS on Dell 5070 and I'm using Shelly Gen 2 devices as BT Proxy.

**Comment by doe81** [comment]
> I'm running HAOS on Dell 5070
If it has an builtin BT try using it or connect a external BT device. Cloud be the proxy feature not sending all info.

**Comment by Misiu** [comment]
I'll check if I have a BT adapter I could use, but ideally, this should work on BT Proxy and BT adapters that are directly connected to the device running HA.

**Comment by pvvx** [comment]
> I'm running Ubuntu and HA in Docker. Im using the built-in BT.

Do you have active scanning enabled?

**Comment by Misiu** [comment]
@pvvx I don't have Bluetooth integration.
As mentioned before I use ESPHome Bluetooth Proxy and Shelly Gen 2 devices, all of them has active scanning set:
![image](https://github.com/pvvx/ATC_MiThermometer/assets/1741838/2e74fb1a-bc75-48f5-b956-2985f7acddf0)

**Comment by pvvx** [comment]
It was a question for @doe81. 

The device only transmits the name to an active scan request.
The name can be accepted by the adapter if there is another actively scanning device on the airwaves.
And also, when the thermometer is included in the function of the Le Long Range mode - "Extended Advertisements". Then the length of the advertising message is not limited and the name is always transmitted.

**Comment by pvvx** [comment]
The source of the glitches has been found. But the reason is unknown.
The nonsense carries "Bluetooth" integration:

```
2023-12-01 21:01:05.487 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci1 (8C:88:2B:00:E7:EA) [connectable]: 58:2D:34:14:50:87 AdvertisementData(local_name='CGG_145087', service_data={'0000fcd2-0000-1000-8000-00805f9b34fb': b'@\x00\xfc\x01d\x02]\x08\x03\x1f\x11', '0000fe95-0000-1000-8000-00805f9b34fb': b'PXH\x0b\xd6\x87P\x144-X\r\x10\x04\xd8\x00\xa9\x01'}, rssi=-73) match: set()
```
Some kind of mixture of MiHome and BTHome.

But in reality the device transmits the following:
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/ae26642c-cb28-4ce3-8366-34937b4033dc)

That is, everything is normal and clearly in the BTHome v2 format.

btmon -i 1
```
> HCI Event: LE Meta Event (0x3e) plen 44
      LE Extended Advertising Report (0x0d)
        Num reports: 1
        Entry 0
          Event type: 0x0013
            Props: 0x0013
              Connectable
              Scannable
              Use legacy advertising PDUs
            Data status: Complete
          Legacy PDU Type: ADV_IND (0x0013)
          Address type: Public (0x00)
          Address: 58:2D:34:14:50:87 (Qingping Electronics (Suzhou) Co., Ltd)
          Primary PHY: LE 1M
          Secondary PHY: No packets
          SID: no ADI field (0xff)
          TX power: 127 dBm
          RSSI: -75 dBm (0xb5)
          Periodic advertising interval: 0.00 msec (0x0000)
          Direct address type: Public (0x00)
          Direct address: 00:00:00:00:00:00 (OUI 00-00-00)
          Data length: 0x12
        02 01 06 0e 16 d2 fc 40 00 e4 01 64 02 67 08 03  .......@...d.g..
        a5 10                                            ..
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Service Data: Unknown (0xfcd2)
          Data: 4000e4016402670803a510
@ MGMT Event: ADV Monitor Device Found (0x002f) plen 34
        Handle: 0
        Address: 58:2D:34:14:50:87 (Qingping Electronics (Suzhou) Co., Ltd)
        Addr Type: 1
        RSSI: -75
        Flags: 0x00000000
        AD Data Len: 18
        AD Data: 0201060e16d2fc4000e4016402670803a510
```

**Comment by pvvx** [comment]
[Already.](https://github.com/Bluetooth-Devices/bthome-ble/issues/96)

**Comment by pvvx** [comment]
> So this should be reporter in HA Core? Or in BTHome repo?

Bluez caches names and stuff. But HA doesn’t know about this or hides it, because they chose the most buggy option - Bluez.

https://stackoverflow.com/questions/43446918/bluez-showing-old-cached-data-on-dbus
https://github.com/home-assistant/operating-system/commit/f8f2e61967eab33209531e932e7e98b3c8efc1a7

**Comment by pvvx** [comment]
> I'll check if I have a BT adapter I could use, but ideally, this should work on BT Proxy and BT adapters that are directly connected to the device running HA.

If the proxy does not report the device name, how will it reach the HA?



> I have several named devices. So it works.
> 
> * if you rename the device after it is detected restart HA and it will detect the new name.
> * if you rename the device after it is configured remove the device and restart HA and it will detect the new name

This doesn't work 90% of the time.
BLE devices transmit the name upon active scanning request. But, if active scanning is enabled, then the batteries of your devices will be drained much faster from the additional transmission each advertising period.

**Comment by doe81** [comment]
> > I'm running Ubuntu and HA in Docker. Im using the built-in BT.
> 
> Do you have active scanning enabled?
> 
> ![image](https://private-user-images.githubusercontent.com/12629515/287299354-775731d3-959c-4b89-ae30-f6c53672ec76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Mjk4MTQsIm5iZiI6MTcwMTcyOTUxNCwicGF0aCI6Ii8xMjYyOTUxNS8yODcyOTkzNTQtNzc1NzMxZDMtOTU5Yy00Yjg5LWFlMzAtZjZjNTM2NzJlYzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDIyMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NTMzNjRkZDUyZTZhZTQ5NzZiODZlOGYzZTI1NjQ3YjM4MjQxNmJmOGUyNmU5NjgxNzkxMTNmNzEwZDBiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WctwsbO1L6VhAOyJUB4gENRsrOWqBkKhTa8zmwY3m1U) ![image](https://private-user-images.githubusercontent.com/12629515/287299385-b4835370-996f-4c35-882a-0510035ff2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3Mjk4MTQsIm5iZiI6MTcwMTcyOTUxNCwicGF0aCI6Ii8xMjYyOTUxNS8yODcyOTkzODUtYjQ4MzUzNzAtOTk2Zi00YzM1LTg4MmEtMDUxMDAzNWZmMmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDIyMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZjMxYTJiYjA2ZDY2ODAyNWMzOWJhMWVmN2JhNDgwNWU2OTYwYzJkMmJkZjc3MmM0ZmQzZGJkMDQ5YTBlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cf6bUxRej6ci4-0LW6Ou7ekPqH9I6mID9OdbvLqUDSU)

Yes, I hade active scanning enabled. Should I select passive scanning instead?

**Comment by pvvx** [comment]
https://community.home-assistant.io/t/passive-ble-monitor-integration/303583/586
