### ISSUE TITLE
Tuya TH05

### ISSUE THREAD

**Issue by Monacoslo** [pvvx/ATC_MiThermometer#427]
Please add support to very similar and very popular (constantly on promotion on AliExpress) Tuya TH05 sensor 
![PXL_20231201_124318378](https://github.com/pvvx/ATC_MiThermometer/assets/47989822/39af00b3-7ba0-4e50-b8c9-390081fcbad3)
![PXL_20231201_125632884](https://github.com/pvvx/ATC_MiThermometer/assets/47989822/e85d1e4f-f11e-429e-a3e7-7494bb64561c)

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/discussions/423
