### ISSUE TITLE
Z2M - CGDK2 Not supported

### ISSUE THREAD

**Issue by szbbalint** [pvvx/ATC_MiThermometer#429]
In Z2M 1.34.0 my qingping cgdk2 is not supported after flash zigbee firmware.
I flashed it about a month ago with the telink flasher, and i think (it was too long ago) i flashed the version 4.0 without any problem. After flash completed 100% i restarted the device (reinserted the battery) and after that is added it to z2m. It shows up, but not supported as in the picture. 

![Képkivágás](https://github.com/pvvx/ATC_MiThermometer/assets/60071017/cd3a96ba-115a-4efb-9975-f851c0f237ba)

Does anyone added cgdk2 succesfully?

**Comment by pvvx** [comment]
Works in ZHA without any problems.
I don't use Z2M.
