### ISSUE TITLE
Strange readings since 4.6 update

### ISSUE THREAD

**Issue by Toniob** [pvvx/ATC_MiThermometer#442]
Hello,

I’m having strange readings since the last update.
![Screenshot 2023-12-17 at 23-42-40 Historique – Home Assistant](https://github.com/pvvx/ATC_MiThermometer/assets/113461/e7fd715e-6eab-417d-a7ce-962321da7979)
As you can see, sometimes, the value sent by the sensor is wrong. These are the spikes on the graph. Strangely, the wrong value is always the same and doesn’t change.
![Screenshot 2023-12-17 at 23-46-41 Historique – Home Assistant](https://github.com/pvvx/ATC_MiThermometer/assets/113461/7fc5fc90-a080-4550-9e42-04eb4d0d8e1c)
Here, you can see the moment I updated the sensor and its behavior after that.

**Comment by Toniob** [comment]
I have the same behavior on several sensors (they all are LYWSD03MMC 1.6). I’ve updated them all. 2 out of 6 do not have this behavior. I may be wrong, but those two were updated from 4.5 version, where the others with the issue were running the 4.3 version.

**Comment by pvvx** [comment]
These are already known problems associated with the integration of BTHome into Home Assistant.

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/418
https://github.com/pvvx/ATC_MiThermometer/issues/405

**Comment by Toniob** [comment]
That’s ok, thanks. I’ve deleted the sensors from homeassistant, put them back, and it’s ok now.
