### ISSUE TITLE
Small Tuya Temperature Sensor

### ISSUE THREAD

**Issue by artur1702** [pvvx/ATC_MiThermometer#454]
Is there a chance it will work with this firmware?  Telink Flasher does not recognize it.

![IMG_20231227_153221073](https://github.com/pvvx/ATC_MiThermometer/assets/11067126/112b3f08-b7cb-46df-a458-8996ac04abcb)
![IMG_20231227_153257935](https://github.com/pvvx/ATC_MiThermometer/assets/11067126/8cd00fcf-d097-4ff8-9133-bdc00d926da4)
![IMG_20231227_153423079](https://github.com/pvvx/ATC_MiThermometer/assets/11067126/bd5de50d-1346-4998-84c2-a2da2627913d)
![IMG_20231227_153435890](https://github.com/pvvx/ATC_MiThermometer/assets/11067126/1cd73e7d-d721-4e7b-844c-3c6e85cc4f66)

**Comment by pvvx** [comment]
https://github.com/pvvx/THB2

**Comment by pvvx** [comment]
[BTHome](https://bthome.io/) format
