### ISSUE TITLE
Zigbeefied LYWSD03MMC Temperature and Humidity reporting values.

### ISSUE THREAD

**Issue by DirkTas67** [pvvx/ATC_MiThermometer#462]
Hello,

I recently discovered that I could flash zigbee firmware for the LYWSD03MMC. I did this with 2 of my devices and I want to display 2 decimals behind the dot, is this possible and what is the value/parameter I have to change for this value to display in Home Assistant?

Dirk,

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc?tab=readme-ov-file#display-decimal-places-for-temperature-humidity-and-battery-charge-in-zha
