### ISSUE TITLE
Unable to pair / join Zigbee network after successful flash (LYWSD03MMC)

### ISSUE THREAD

**Issue by knovoselic** [pvvx/ATC_MiThermometer#464]
I've received today two LYWSD03MMC monitors. I've flashed both using https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html. The first one connected to my Zigbee network relatively quickly (probably within less than a minute), while the second one is not connecting at all.

Is there anything I can do to debug this? The device is working fine, it's just that it will not join the Zigbee network no matter what I do. I've tried replacing battery from the device that has joined successfully, pulling the batter out and holding GND + RST for 7 seconds, until it restarts and shows --. No matter what I do it does not even try to join the Zigbee network. The bluetooth icon is always present.

Any ideas what do to next?

**Comment by lbarjak** [comment]
Repeat the flash.

Kristijan Novoselić ***@***.***> ezt írta (időpont: 2024.
jan. 9., K 19:02):

**Comment by knovoselic** [comment]
@lbarjak Is there a way to do it via OTA, or do I have to flash it via UART now?

**Comment by lbarjak** [comment]
Do it with uart instead.

Kristijan Novoselić ***@***.***> ezt írta (időpont: 2024.
jan. 10., Sze 7:36):

**Comment by knovoselic** [comment]
Thanks!

**Comment by adrianjagielak** [comment]
For anyone facing the same issue and not wanting to solder: the solution is to just short the reset and gnd again and again and again until it finally works and joins the Zigbee network.
