### ISSUE TITLE
Battery Drain on Xiaomi Mijia (LYWSD03MMC) with Zigbee Version of firmware.

### ISSUE THREAD

**Issue by mrkaqz** [pvvx/ATC_MiThermometer#465]
I have flashed 2 of my Xiaomi Mijia LYWSD03MMC with the Telink Flasher 7.4 with Zigbee radio.
Then paried it with Z2MQTT on my HA.

After using for a while notice that the batter was low, then I changed to new battery still observed the drainage of battery.

Anyone experience the same?

![Screenshot 2024-01-13 140133](https://github.com/pvvx/ATC_MiThermometer/assets/6989907/2423e6e3-f348-406e-b9e9-cd90470827d2)

![411518671_1101103794413297_6077785754712049090_n](https://github.com/pvvx/ATC_MiThermometer/assets/6989907/c7b45ad4-da94-477a-b970-4601126e1671)

**Comment by Routout** [comment]
Yes, Battery last only couple of weeks. Going to revert back to BT.

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc/issues/37
