### ISSUE TITLE
Диапазон смещения влажности

### ISSUE THREAD

**Issue by DedkovArtem** [pvvx/ATC_MiThermometer#466]
Имею в наличии несколько датчиков LYWSD03MMC у которых необходимо установить коррекцию влажности больше чем 12,7%. Насколько критично корректировать влажность с точностью до 0,1%? Предлагаю сделать её целочисленной

**Comment by pvvx** [comment]
> Имею в наличии несколько датчиков LYWSD03MMC у которых необходимо установить коррекцию влажности больше чем 12,7%.

Испорченных датчиков?

**Comment by pvvx** [comment]
Датчики влажности деградируют. В основном от загрязнений. А если новые - возможно попал флюс при пайке.
Восстановить невозможно. И у датчика будет другая диаграмма линейности и т.д. Т.е. необходимо корректировать и коэф. наклона (множитель) и смещение. Но это всё равно не поможет.

**Comment by DedkovArtem** [comment]
Спасибо за быстрый ответ. Думаю действительно будет проще заменить на новый.

**Comment by pvvx** [comment]
Два Xiaomi LYWSD03MMC B1.9 и B1.4 на одной полке.  
Один с прошивкой Zigbee, другой c BLE. 
Даты выпуска имеют разницу в 1 год.
Никаких коррекций.
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/c1a56781-e9ed-4f27-b776-6fe1e1605d79)
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/bb5c1164-82a4-4e63-bf83-d532fb929e75)
Но врут, т.к. по расчету точки росы у них разница:
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/30b9623c-5e92-44a5-a918-44d4c0e2a610)
