### ISSUE TITLE
 LYWSD02MMC support

### ISSUE THREAD

**Issue by Avalonnw** [pvvx/ATC_MiThermometer#467]
Hi,
I've got a LYWSD02MMC version (with bigger display) however when I try to connect to it I get message: `Not found Telink OTA service!`
Is this device not supported? Is there a chance for its support in the future?

**Comment by pvvx** [comment]
This repository is called: 

## Custom firmware for BLE thermometers **on the Telink chipset**.

https://pvvx.github.io/LYWSD02/

**Comment by tbaumann** [comment]
> This repository is called:
> ## Custom firmware for BLE thermometers **on the Telink chipset**.
> 
> https://pvvx.github.io/LYWSD02/

What do you mean by that? Currently only supported by vendor firmware?

**Comment by pvvx** [comment]
This device has a different chipset. I do not do it.
