### ISSUE TITLE
MJWSD05MMC activating hangs, no response for half an hour

### ISSUE THREAD

**Issue by weareoutman** [pvvx/ATC_MiThermometer#505]
Thanks for making the tool, I have made it work with LYWSD03MMC, but have no luck with MJWSD05MMC.

logs:

```
1:07:09 PM: Searching for devices
1:07:12 PM: Connecting to: MJWSD05MMC
1:07:13 PM: Hardware Revision String: V2.3
1:07:13 PM: Software Revision String: 0026
1:07:13 PM: Firmware Revision String: 0026
1:07:13 PM: Detected Mi device
1:07:13 PM: Connected
1:07:17 PM: Activating now, please wait...
```

The log stops here for half an hour, when I open the browser console,  the temperature reports normally every few minutes.

Console logs:

```
Found MiTemp characteristic
TelinkMiFlasher.html:1790 Found Main service
TelinkMiFlasher.html:1790 Found enc_10 char
TelinkMiFlasher.html:1790 Found enc_19 char
TelinkMiFlasher.html:1790 Status: 'MJWSD05MMC HW:V2.3' connected, you can now Do the Activation to either get the Token or flash a new Firmware
TelinkMiFlasher.html:1790 Send: a2000000
TelinkMiFlasher.html:1790 Enc_19: 000000000200
TelinkMiFlasher.html:1790 Send: 00000101
TelinkMiFlasher.html:1790 Enc_19: 01000100000000626c742e332e3168633170346e
TelinkMiFlasher.html:1790 Enc_19: 020075386b343030
TelinkMiFlasher.html:1790 Send: 00000100
TelinkMiFlasher.html:1790 Send: 15000000
TelinkMiFlasher.html:1790 Send: 000000030400
TelinkMiFlasher.html:1790 Temp: 29.3°C, Humi: 62%, 3190 mV
```

**Comment by pvvx** [comment]
On thermometers with buttons, activation requires using the buttons as described in the instructions included in the box. Another instruction is contained in the MI-Home upon activation.

**Comment by Bandit** [comment]
This part was what was critical for it to work for me:

> Press and hold both buttons for a few seconds until the screen blink (device resets). Next, briefly press the top side button, then briefly press the bottom button. The Bluetooth icon will start flashing. Next 'Connect' and 'Do Activation' in [TelinkMiFlasher](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html).
