### ISSUE TITLE
Battery stucks at 100% for months with LYWSD03MMC

### ISSUE THREAD

**Issue by cdenfert** [pvvx/ATC_MiThermometer#507]
Hello,

I have a problem with 2 of my LYWSD03MMCs, the battery has been stuck at 100% for months. Hardware version is B1.7 and B1.9, firmware 4.6 & 4.7
It didn't behave like this before I changed the batteries.
![image](https://github.com/pvvx/ATC_MiThermometer/assets/72680798/fd0d6c3b-4de7-4726-aeb6-aeff29049fa0)
![image](https://github.com/pvvx/ATC_MiThermometer/assets/72680798/6fe3ac6b-5983-4ff7-86a7-e2729cd0e591)
![image](https://github.com/pvvx/ATC_MiThermometer/assets/72680798/dd8675b0-0f36-45fe-abc4-acfecf00443a)
![image](https://github.com/pvvx/ATC_MiThermometer/assets/72680798/466de12d-b0f7-47ad-897d-4c1ae3cfa88a)

Is it a hardware problem?

Thank you in advance

**Comment by pvvx** [comment]
Battery voltage above 2950 mV is considered 100%.
Rated voltage CR2032 3.0 V without load.
