### ISSUE TITLE
LYWSD03MMC flashing

### ISSUE THREAD

**Issue by redixyz** [pvvx/ATC_MiThermometer#520]
LYWSD03MMC with the official frimware v2.11

I tried flashing it to the original 1.0 version so that I could install custom frimware after that.

**logs:**
<img src="https://github.com/pvvx/ATC_MiThermometer/assets/117117297/f3152ce2-158c-4d7e-b546-3f31fb718e98" alt="drawing" width="200"/>

**Ota flasher:**
<img src="https://github.com/pvvx/ATC_MiThermometer/assets/117117297/6c81eaef-065f-4616-8045-b1b4bb00aace" alt="drawing" width="200"/>

**Comment by pvvx** [comment]
[README](https://github.com/pvvx/ATC_MiThermometer/tree/master?tab=readme-ov-file#custom-firmware-for-ble-thermometers-on-the-telink-chipset):
**Warning: [Firmware LYWSD03MMC version 2.1.1_0159 is temporarily not supported!](https://github.com/pvvx/ATC_MiThermometer/issues/378#issuecomment-1756740533)**
