### ISSUE TITLE
Count/switch not visible in advertisments

### ISSUE THREAD

**Issue by vahempio** [pvvx/ATC_MiThermometer#533]
Hi,

(First, thank you for this incredible work!)

On a LYWSD03MMC, I tried to have the pulse counter from a reed switch connected to P8. According to the Readme.md (https://github.com/pvvx/ATC_MiThermometer?tab=readme-ov-file#reed-switch-or-button-functions), there is nothing to do for having the value in advertisments (I don't need "events" on pulses).

But there is no traces of pulse counter in advertisments, according to nrfconnect (i decoded only temp/hum/voltage/power, no count value). Even with the activation of events, there is no changes in the adv.

![Screenshot_20240813_084153_nRF Connect](https://github.com/user-attachments/assets/014ed39e-151c-4911-b187-ac5ffa58072f)

Question: how to enable counter value in adv? Thanks a lot!

**Comment by pvvx** [comment]
Support for receiving and transmitting a reed switch counter is only available in the [BTHome](https://bthome.io/) standard.

In [TelinkMiFlasher](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) you need to set the reed switch usage option:
![image](https://github.com/user-attachments/assets/d83467f7-292a-47a9-8ff5-02d8f18b992b)

**Comment by vahempio** [comment]
Thank you for the fast answer!
My config was correct, but I was on the 4.7 fw version: after an upgrade to 4.8 beta fw, it works like a charm, thank you very much!
