### ISSUE TITLE
Для двух датчиков LYWSD03MMC перешитые в Zigbee получаю ошибку

### ISSUE THREAD

**Issue by almirus** [pvvx/ATC_MiThermometer#543]
Приветствую, не знаю обновление ли прошивок устройств на **3001-0122**, или обновление прошивки координатора egony cp2652p на **20240710** привели к тому что теперь периодически получаю всплывашку в z2m

`error 2024-09-17 21:38:32z2m: Failed to configure 'Датчик температуры в спальне', attempt 3 (Error: Bind 0xa4c1385678f731eb/1 msTemperatureMeasurement from '0x00124b0022810ef5/1' failed (ZDO error: bind failed with status 'TABLE_FULL' (140)) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1126:36)
`
ошибка для обоих датчиков, при том что устройства zigbee без проблем добавляются, сами датчики сидят на разных роутерах.

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc/issues/114
