### ISSUE TITLE
Configurable sensor accuracy

### ISSUE THREAD

**Issue by FBlass** [pvvx/ATC_MiThermometer#550]
Hi everyone,

it is nice that the custom firmware has a increased accuracy, up to 0.01. However it do not need this high accuracy and would prefer to configure this for humidity and temperature.
For temperature 0.1 is enough for me, for humidity no decimal precision is required for me. Is it possible to make this configurable in the firmware?

Thanks for this awesome project!

**Comment by pvvx** [comment]
The digit capacity of the readings is set in an external program. 
For example, in Home Assistant:
![image](https://github.com/user-attachments/assets/fbddfc3b-dc7c-4683-916b-a8f6997a06ba)
