### ISSUE TITLE
Firmware compatibility with CGG1-T ?

### ISSUE THREAD

**Issue by vincedarley** [pvvx/ATC_MiThermometer#554]
Hi - I have a few of these "T" versions of the QingPing sensor, which can run over bluetooth or Thread, and support HomeKit. Are you aware if the custom firmware works on them? (And whether it could support Thread)?  Thx

**Comment by pvvx** [comment]
I don't have CGG1-T and I don't know what chipset is used.

**Comment by vincedarley** [comment]
If it helps, there are teardown pictures of it here:
https://device.report/m/0857ffc50bc59be35306e9dac1fd1874658586fce5e9a0592d30c2f91a73bd46.pdf

Particularly the last picture is close enough to see writing on the main
chip. Vince

[image: image.png]

**Comment by vincedarley** [comment]
Looks to be N52840, which is a version of this
https://www.nordicsemi.com/Products/nRF52840 I think.

Vince.

**Comment by pvvx** [comment]
nRF52x chips have OTA firmware locked with a key.
Use JTAG.
