### ISSUE TITLE
Firmware ATC_47 and FW ATC_48 report different sensors for the same LYWSD03MMC  v1.4 Hardware

### ISSUE THREAD

**Issue by jksmurf** [pvvx/ATC_MiThermometer#558]
I have two LYWSD03MMC sensors HW rev 1.4. 

I appreciate HA questions go elsehwere but my question here is about the sensors. 
Why does FW 47 and FW 48 report different sensors for the same Hardware?

LR
9:53:06 PM: Hardware Version: LYWSD03MMC B1.4, Software **Version: 4.7**, Sensor: SHTC3 (SHTV3)
9:53:06 PM: Custom config HEX string: 55071000002804a9313180b4

10:06:15 PM: Hardware Version: LYWSD03MMC B1.4, Software **Version: 4.8**, Sensor: SHT4x
10:06:15 PM: Custom config HEX string: 55071000002804a9313100b4

MB
10:16:07 AM: Hardware Version: LYWSD03MMC B1.4, Software **Version: 4.7**, Sensor: SHTC3 (SHTV3)
10:16:07 AM: Custom config HEX string: 55071000002804a9313180b4

9:58:01 PM: Hardware Version: LYWSD03MMC B1.4, Software **Version: 4.8**, Sensor: SHT4x
9:58:01 PM: Custom config HEX string: 55071000002804a9313100b4

The table in pvvx documentation suggests SHTC3 is correct for v1.4HW?

I am asking as one of my apparently identical devices connects via BTHome in HA, the other does not and I cannot work out why. I took the battery out, I tried resetting, I flashed to v48 (beta).

When I flash them to Zigbee Z03MM_v0123.bin BOTH are recognised and work fine, so they do work, but one of them does not seem to like BTHome, even if it appears it has identical FW to the other.

Any ideas on that?

![WhichHW](https://github.com/user-attachments/assets/e0686622-53b6-4e01-a307-eca2621b1259)

**Comment by pvvx** [comment]
Version 4.8 is still in beta. There are many changes in this version and not everything is tested yet.
