### ISSUE TITLE
Main loop is blocking blt_sdk_main_loop. Is it intended?

### ISSUE THREAD

**Issue by danergo** [pvvx/ATC_MiThermometer#563]
This is your current start of `main_loop`:

```
void main_loop(void) {
	blt_sdk_main_loop();
	while (clock_time() -  utc_time_sec_tick > utc_time_tick_step) {
		utc_time_sec_tick += utc_time_tick_step;
		utc_time_sec++; // + 1 sec
	}
...
}
```

Although I haven't checked, but this seems to be blocking the main_loop for 1 second, hence blocking also `blt_sdk_main_loop`.

I also checked ATC's version:

```
void main_loop(){	
	if((clock_time()-last_delay) > 5000*CLOCK_SYS_CLOCK_1MS){//main loop delay
        ...
        }
        
        blt_sdk_main_loop();
	blt_pm_proc();	
}
```
This seems not blocking the main_loop, letting blt_sdk_main_loop run as fast as possible. Is this something you wanted to avoid?

And what's the reason of not using `blt_pm_proc`, which seems to be a manager of some low-power features?

> Function blt_pm_proc is added in PM configuration of main_loop. This function must be placed at the end
of main_loop to ensure it is immediate to blc_sdk_main_loop in time, since blt_pm_proc needs to configure
low power management according to different UI entry tasks.

No offense at all, I just wish to understand what's going on :)

**Comment by pvvx** [comment]
> This is your current start of main_loop:

The maximum execution time of this loop is 10 iterations, which means the execution time is less than 1 µs. The maximum pause before executing this loop is always less than 11 seconds, and the clock_time() counter is usually limited to 260 seconds.

> I also checked ATC's version:

Different SDKs are used and most procedures are replaced with their own.

Learn to look at code correctly.

**Comment by danergo** [comment]
Yeah man, sorry. Realized almost immediately after posting this issue but I couldn't delete it.

I misread the while loop in the beginning.
