### ISSUE TITLE
Trying to `Select an advertising device` in Advertising.html gives TypeError

### ISSUE THREAD

**Issue by mvadu** [pvvx/ATC_MiThermometer#57]
[Advertising.html](https://pvvx.github.io/ATC_MiThermometer/Advertising.html)

23:45:27: Requesting Bluetooth Scan...
23:45:31: > Requested Mijia_2
23:45:31: Watching advertisements from "Mijia_2"...
23:45:31: Argh! TypeError: device.watchAdvertisements is not a function

Device info (from firmware update page)
11:53:11 PM: Searching for devices
11:53:23 PM: Connecting to: Mijia_2
11:53:46 PM: Detected custom Firmware
11:53:46 PM: Hardware Version: LYWSD03MMC, Software Version: 2.3
11:53:46 PM: Custom config: [3, 0, 0, 0, 80, 4, 191, 124, 49, 56, 0]

**Comment by pvvx** [comment]
https://stackoverflow.com/questions/64654250/device-watchadvertisements-is-not-a-function-web-bluetoothchrome

**Comment by mvadu** [comment]
@pvvx that link does not tell me anything I can check as a consumer, right? I tried with two smartphones, and a laptop to get same behavior. Could you please try once from your end and confirm if its still working?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/109264379-f54c5980-7815-11eb-89fa-c85cc4c074ff.png)

**Additional tests:**
https://googlechrome.github.io/samples/web-bluetooth/
Watch Advertisements (Promises) / Watch Advertisements (Async Await) - watch advertisements from a BLE device.

**Implementation Status:**
https://github.com/WebBluetoothCG/web-bluetooth/blob/main/implementation-status.md#gatt-communication-api

**Comment by mvadu** [comment]
Thank you.. I was thinking this page is where I can select the advertisement type? In your code you have old atc version and your own version. Where do I select the type of advertisement sent from thermometer

**Comment by mvadu** [comment]
I found the advertising type dropdown in main flasher page itself.
