### ISSUE TITLE
THB1 shown as THWL

### ISSUE THREAD

**Issue by Mezzo1973** [pvvx/ATC_MiThermometer#572]
I purchased the THB1 Bluetooth Temperature Humidity Sensor from tuya. Now I wanted to flash it on zigbee, but without success. The Bluetooth name of the device is THWL and therefore the sensor cannot be paired and the new firmware cannot be flashed OTA. Does anyone have an idea why this is or a solution? Thank you!

**Comment by pvvx** [comment]
https://github.com/pvvx/THB2
