### ISSUE TITLE
Incoherent battery readings (also not limited to 100%)

### ISSUE THREAD

**Issue by znanev** [pvvx/ATC_MiThermometer#58]
One of my MHO-C401 devices started to give strange readings for the battery from time to time. As I log those readings in Home Assistant, you can see the strange fluctuations on this graph:

![image](https://user-images.githubusercontent.com/20048364/109279500-b87e6380-7811-11eb-8f5a-7a269e6a0650.png)

It appears that sometimes the battery values jump to over 200% (up to 211% in fact). The temperature / humidty measuers at those same times appear perfectly normal, so the strange fluctuations affect the battery measurements only.

I'm not sure why this can be, as the settings for all my MHO-C401 devices are the same, running the same version of the firmware (currently v2.3p). Following is the battery graph of the other MHO-C401 sensor, covering the same time interval:

![image](https://user-images.githubusercontent.com/20048364/109279594-d946b900-7811-11eb-9ba1-ec171f30e0a9.png)

As you can see, battery values appear perfectly normal.

**Comment by pvvx** [comment]
The current version of the device software has 4 types of battery percentage transmission packets. Your Home Assistant build probably doesn't know all versions and is confusing something.

**Comment by znanev** [comment]
I'm only using the unencrypted Mijia format (3 in your list above). Battery measurements are coming as value of general attribute 0x100a. So the erroneous values are definitely coming from the device and are in no way linked to Home Assistant.

I'll try to capture some of the incoherent frames.

**Comment by znanev** [comment]
Just checked the advertisement packets at the moment when Home Assistant was showing the unusually high values of 211% - 213%. Indeed no incoherent battery readings are coming in the frames, received from the device.

So the bug is probably a parsing error in [Passive BLE Monitor integration](https://github.com/custom-components/ble_monitor) component. I'll check there. 

Sorry for the false alarm, closing this issue.

**Comment by pvvx** [comment]
> I'm only using the unencrypted Mijia format (3 in your list above).

https://github.com/custom-components/ble_monitor recommends a different type of Advertising format.
