### ISSUE TITLE
what temp sensors are supported? 

### ISSUE THREAD

**Issue by 0xDEADBEEF-ASAP** [pvvx/ATC_MiThermometer#580]
LYWSD03MMC

SHT30, SHT31, SHT35, SHT40, SHT41?

I want to replace internal SHT with external one.

**Comment by pvvx** [comment]
LYWSD03MMC: SHTV3 or SHT4x

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/571
