### ISSUE TITLE
[feature request] MJWSD05MMC: add possibility to hide chinese weekday characters

### ISSUE THREAD

**Issue by eni23** [pvvx/ATC_MiThermometer#583]
On MJWSD05MMC with enabled display, the LCD is showing Chinese characters, which seem to be the weekday:

![PXL_20241219_202915564~2](https://github.com/user-attachments/assets/afdd3cd7-7e47-428b-ab89-86510592e863)

This feature request is asking for a flag in the configs to not display this characters at all, as most non-CN users won't understand them anyway, and the display would look much cleaner and less "cheap" whitout them.

**Comment by pvvx** [comment]
| Воскресенье | Понедельник | Вторник |  Среда | Четверг | Пятница | Суббота |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|  Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
| 週日 | 週一 | 週二 | 週三 | 週四 | 週五 | 週六 |
