### ISSUE TITLE
Advertising types?

### ISSUE THREAD

**Issue by ralf-e** [pvvx/ATC_MiThermometer#6]
Is there already a documentation of the different advertising types that are now possible

**Comment by rjblake** [comment]
@ralf-e - Victor shared this in response to my question [here](https://github.com/pvvx/ATC_MiThermometer/issues/5#issuecomment-753515459)

As below (unless changed recently)
`struct _packed_ {
	uint8_t		size;	// = 18
	uint8_t		uid;	// = 16, 16-bit UUID
	uint16_t	UUID;	// = 0x181A, GATT Service 0x181A Environmental Sensing
	uint8_t		mac[6];
	int16_t		temperature; // x 0.01 degree
	int16_t		humidity; // x 0.01 %
	uint16_t	battery_mv; // mV
	uint8_t		battery_level; // %
	uint8_t		counter; // measurement number
	uint8_t		flags; 
} adv_custom_t;`
