### ISSUE TITLE
[Feature Request] Two point calibration

### ISSUE THREAD

**Issue by shyney7** [pvvx/ATC_MiThermometer#61]
A feature to compensate the non-linearity of sensor data would be nice for manual calibration. 
Something like this was implemented in this script to read the data: https://github.com/JsBergbau/MiTemperature2#two-point-calibration

Thanks to @rjblake that mentioned it here how to calibrate the sensor https://github.com/pvvx/ATC_MiThermometer/issues/60#issuecomment-787956694

**Comment by pvvx** [comment]
This applies to the original firmware - built-in offset of + 5%
The stability of the sensor readings also depends on the supply voltage, temperature, and vapor composition. More than + -1% calibration is not possible. The calibration and deviation table is non-linear and two-point snapping gives nothing.
