### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by GHRoss** [pvvx/ATC_MiThermometer#62]
Hello,

I'm using the script at the bottom of [this ](https://hackaday.com/2020/12/08/exploring-custom-firmware-on-xiaomi-thermometers/) article and was wondering if there was a way to implement some sort of authentication with the current 2.4 firmware?

**Comment by pvvx** [comment]
Authentication of what?

There is no authentication on the link https://hackaday.com/2020/12/08/exploring-custom-firmware-on-xiaomi-thermometers/

The firmware version > 2.2 has bindkey encryption, as well as pincode protection of the connection.
![image](https://user-images.githubusercontent.com/12629515/109707739-925b1980-7bab-11eb-83e8-dfbc08e94860.png)
![image](https://user-images.githubusercontent.com/12629515/109707748-95560a00-7bab-11eb-90ab-f771a87749cf.png)
https://github.com/pvvx/ATC_MiThermometer/blob/master/test_adv_key.py
