### ISSUE TITLE
Unable to fully disable comfort indicator on MHO-C401

### ISSUE THREAD

**Issue by kelchm** [pvvx/ATC_MiThermometer#63]
I recently received a pair of MHO-C401's, but unlike the LYWSD03MMC I've found that I'm unable to completely disable the 'comfort' indicator by editing the configuration via TelinkMiFlasher.html. The parenthesis and asterisk looking indicator to the left seem to always be visible.

Firmware Version: v2.4

![IMG_2361](https://user-images.githubusercontent.com/172301/109748437-df88bc80-7ba6-11eb-9f04-3eb713ed46fb.jpg)

**Comment by pvvx** [comment]
Yes. These segments of the indicator on MHO are associated with a comma sign.
https://github.com/znanev/MHO-C401#segments

**Comment by kelchm** [comment]
Makes sense, thanks for the explanation.
