### ISSUE TITLE
Can't set the RF tx power

### ISSUE THREAD

**Issue by oangelo** [pvvx/ATC_MiThermometer#69]
I am tring to set the tx power on Telink Flasher, but, when I press the button "Send Config" the minimum power is automaticaly set. "Set default" and  then "Send Config" works to go back to the default. I wish to improve the tx power to be able to receive the data a bit more distant from my bluetooth hub. This hapens both in my smartphone and on a linux browser.

**Comment by pvvx** [comment]
?
![image](https://user-images.githubusercontent.com/12629515/110608898-bc10d380-819d-11eb-9448-3acbee9cd616.png)

**Comment by oangelo** [comment]
Today it is working, thanks @pvvx. But, I can not choose the power higher than +3.01 dbm, only lower. Higher power options were showing yesterday. Is 3.01dbm the maximum power?

**Comment by pvvx** [comment]
The microcircuit has 2 antenna options (VBAT and VANT) and an RF power supply. The second option works with reduced power on the current board ...

**Comment by ibamsey** [comment]
So what is the highest power setting that can be achieved on the LYWSD03MMC ?

**Comment by pvvx** [comment]
> So what is the highest power setting that can be achieved on the LYWSD03MMC ?

Depends on the internal resistance of the battery.
The chip has tx output power up to +10 dB

**Comment by pvvx** [comment]
Replacing the CR2032 with a more powerful battery allows for higher TX RF power to +10 dB. A pulse current of 30 mA is required at 3.3 V.
In TelinkMiFlasher.html, [change line](https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html#L28): 
```` const MAX_RF_TX_Power = false; ````
to 
```` const MAX_RF_TX_Power = true; ````
![image](https://user-images.githubusercontent.com/12629515/144742358-f55e725b-2d52-4591-9171-e2630db71bd6.png)
