### ISSUE TITLE
With BLE fitness trackers ?

### ISSUE THREAD

**Issue by mr-sneezy** [pvvx/ATC_MiThermometer#71]
I'll post this as an idea rather than a feature request, as it's probably not possible or in the scope of the original environmental sensor integration concept but I won't know unless I ask...

Does anyone other than me wonder if the same concept used with MiThermometer could be used with cheap hackable BLE fitness wrist bands that have body temp, heart rate, blood oxygen monitoring etc ? 

I.E. to reflash them with branched firmware that will in similar fashion advertise body data to HA via the ESPhome BLE hub without any OEM apps or cloud based monitoring (privacy intrusion). 
The benefits of this would be detailed health monitoring at home (particularly during sleep) and HA automations based on the sensors, with warnings/logs about high heart rate, low blood oxygen etc etc. 

Thoughts anyone ?

**Comment by atc1441** [comment]
That is possible the same way yes

Actually i got 20 of some 2€ fitness tracker with telink soc just never started with them as no one could benefit from it, when they are hard to get it doesnt make much sense.
If there is a cheap device widely available it would be perfect

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/110692444-5ea97080-81f7-11eb-9edc-5966e51e43da.png)
![image](https://user-images.githubusercontent.com/12629515/110692611-90bad280-81f7-11eb-9a5d-ca3b4ebf6424.png)
....

**Comment by mr-sneezy** [comment]
Interesting. Clearly you've given the idea some thought. 
I have a couple of China fit bands here too, neither of which I use because I found the OEM apps and firmware too clunky and lacking in some way, like proper at home logging.
Happy to buy another to hack/test if one of the many models is suitable. It does not need much of a display, just enough to see if it's working.

**Comment by pvvx** [comment]
> I.E. to reflash them with branched firmware that will in similar fashion advertise body data to HA via the ESPhome BLE hub without any OEM apps or cloud based monitoring (privacy intrusion).

Unfortunately, ESPHome (ESP32) is very bad at receiving beacons (Advertising Packages).

**Comment by mr-sneezy** [comment]
Ah OK. 
Hey, but isn't that what we are picking up from the reflashed MiThermometers sensors now though ?
(very sorry if I've found a gap in my understanding of the advertising meaning, I know it's not your job to educate me) 

Reason I ask is that ESPHome Hub is what I'm using for the 4x sensors spread all over my house (including one that is inside the fridge) with reading reliability.
