### ISSUE TITLE
time drift Xiaomi Mijia

### ISSUE THREAD

**Issue by mretegan** [pvvx/ATC_MiThermometer#74]
I have flashed 4 Xiaomi Mijia using v2.4 of the firmware. In addition to temp/humidity, they also display the time. On all devices, I see a positive drift of the time, i.e. today, three weeks after flashing the devices are ~10 minutes ahead, but they don't have the exact drift.

This are the configuration parameters [13, 0, 0, 0, 160, 4, 191, 124, 20, 56, 60].

Any ideas what might be causing this and how to solve it?

P.S. Thanks for the very nice firmware!

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/56
