### ISSUE TITLE
How to stop ExtShow? 

### ISSUE THREAD

**Issue by ChooTingFeng** [pvvx/ATC_MiThermometer#75]
First of all, thanks for this custom firmware, it is so powerful and there's so many settings

Just 1 question, I hit the ExtShow thing that makes it show 1234, a weird face and 99.

And it has been cycling through that, normal temps and humidity, and clock

How do I stop it from showing that 1234 weird face?

Set Default config didn't seem to reset it

**Comment by OmgImAlexis** [comment]
Same issue here. I can't find anything to revert this.

**Comment by PRSXFENG** [comment]
Hey there, I figured out you just have to wait, one of the variables that
was there is time, so just let it sit for 10 minutes or so and it'll be
back to normal again.

**Comment by OmgImAlexis** [comment]
I ended up reflashing. Good to know though.

**Comment by ndrwrbgs** [comment]
For posterity (I stumbled upon this issue via search) - you can also issue a _new_ `Show` command with the time variable set to a low number. It will overwrite the old time.
