### ISSUE TITLE
Connection not possible after flashing the FW to Version 2.9

### ISSUE THREAD

**Issue by Flugente-19** [pvvx/ATC_MiThermometer#80]
Hello pvvx,

today I have flashed the "MHO-C401 Custom Firmware Version 2.9" to my device MHO-C401. The device seems to work properly and I can receive the temperature, the humidity and the battery status with your test program Advertising.ino. Additionaly I'd like to configure the device according to your description, but the connection with the TelinkMiFlasher.html is not possible. On my Windows 10 notebook I have tried to connect to the device with two different browsers (Chrome and Edge) und got the same error in both cases:

![MHO_C401_Error](https://user-images.githubusercontent.com/81471370/112874915-cd297200-90c3-11eb-83b5-ffdf8181db2f.png)

Do you have an idea, how can I solve the issue?

Thank you in advance!

Kind regards
Flugente-19

**Comment by pvvx** [comment]
MHO checked. Works on smartphones with Android and on computers with new BT adapters.

Checked more options for adapters:

![image](https://user-images.githubusercontent.com/12629515/113213875-65b92100-9281-11eb-8ce3-1b5f753ec3f2.png)

Option "1" works well as many others.

Found a variant of bad work with the adapter number "2":

![image](https://user-images.githubusercontent.com/12629515/113214921-d14fbe00-9282-11eb-9aa2-0f4b11c24193.png)

Internal error occurs: _DOMException: GATT operation not permitted._

Later I will try to solve the problem in Telinkmiflasher.html ...

**Comment by pvvx** [comment]
N2 adapter error detected. These are bugs in Windows drivers and adapter. The adapter remembered the MAC from the previously connected bind and pin code and was buggy. Changing the MAC on the device solved the problem.
MHO-С401 firmware and TelinkMiFlasher.html have nothing to do with it.

**Comment by Flugente-19** [comment]
Hello Viktor, thank you for the fast feedback.

Today I checked the connection to the MHO-C401 from my Android smartphone - the connection was possible and the FW configuration could be changed.

But I don't understand, why it was possible to connect and flash your FW from my notebook with the build-in BT 4.2 adapter Intel AC 8265 and afterwards the connection with the same notebook was not possible. I will observe the issue.

Kind regards
Michael
