### ISSUE TITLE
Old Data

### ISSUE THREAD

**Issue by Stolyassa** [pvvx/ATC_MiThermometer#83]
Hello,

I finally can see the data without Mi Phone and Mi Home. Thank you for the project. But, I only can see the last one day of the data. Is this normal? Does flashing deletes device's memory? Is it possible to see older data for months?

I am using https://pvvx.github.io/ATC_MiThermometer/GraphMemo.html this site btw. I didnt get the difference between GraphMemo and others (GraphAtc, GraphAtc1, DevPoint)

**Comment by pvvx** [comment]
The measurement memory has a depth of 19632+ records. The step of recording measurements is set in https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

![image](https://user-images.githubusercontent.com/12629515/113576733-c7361280-9628-11eb-8428-ba28d54ee926.png)

Default 60 x 10 sec = 600 sec.
19632 * 600 / 60 / 60 / 24 = 136 days.

**Comment by Stolyassa** [comment]
Sorry. I don't master Mi device and Bluetooth Low Energy technology. Do I need to set the value 19632 in measure interval text box there?

**Comment by pvvx** [comment]
Not. 
Sets the recording step interval.

**Comment by Stolyassa** [comment]
Oh. Thats working now I guess. Thank you.
