### ISSUE TITLE
OTA flashing with this version ?

### ISSUE THREAD

**Issue by mr-sneezy** [pvvx/ATC_MiThermometer#9]
Hi, just became aware of this version firmware.
To clarify, in the repo's 'About' info it only mentions USB-Serial hard wired flashing for this firmware, does this mean it can not be flashed over the air like the ATC1441 version ?
Thanks.

**Comment by atc1441** [comment]
Hey you can download the complete repo and open the file:

TelinkMiFlasher.html

then you can use it like the other flasher

**Comment by pvvx** [comment]
https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html

**Comment by mr-sneezy** [comment]
Thank you gentlemen.
