### ISSUE TITLE
Custom Firmware and Mi Home App Ios

### ISSUE THREAD

**Issue by lolax80** [pvvx/ATC_MiThermometer#90]
Hallo,

how can i Connect the Display again to the Mi Home App on iOS, After i have the custom firmware on it.
The App can See a new device but cant Connect to ist.
Whats about the Parse Bind key Option.
Can somebody explain it to me? My english isnt the best.

thanx

**Comment by pvvx** [comment]
Custom firmware is not supported in Mi Home.

**Comment by Skyridr** [comment]
> Custom firmware is not supported in Mi Home.
What about other apps?

**Comment by phoberus** [comment]
Is there a possibility, to use it for automation without the GPIO PA5 trigger?
If it is possible with an App, or otherwise I have a Pi
