### ISSUE TITLE
Kalman filter for temperature readings

### ISSUE THREAD

**Issue by gazzat5** [pvvx/ATC_MiThermometer#91]
Hi there, thanks for the great work on this firmware!

Just wondering if you might be able to implement a 'kalman filter' in the firmware to improve temperature readings by using the state history to improve future readings and more closely estimating the actual temperature. This would reduce the flipping between temperature readings when it's close to the next value but not quite there. 

See attached graph for what I'm talking about with regards to the values jumping between two points. 
![Screenshot_20210414-132250_Chrome](https://user-images.githubusercontent.com/5393362/114709866-fdf4e280-9d24-11eb-8291-fbdefd07cbf0.jpg)
Cheers
Garreth

**Comment by pvvx** [comment]
Sensor noise in the range of about + 25C:
![image](https://user-images.githubusercontent.com/12629515/114870135-7c728280-9e00-11eb-9af9-2c4a25e9d5d6.png)
The transmission is carried out with a resolution of 0.01C.

**Comment by pvvx** [comment]
There is an ad format with an accuracy of 0.01 units and no filters are required.
![image](https://user-images.githubusercontent.com/12629515/119632787-cd22c580-be19-11eb-8efc-0ead138dcb46.png)
