### ISSUE TITLE
smartphone connects without pin

### ISSUE THREAD

**Issue by 50494554524F** [pvvx/ATC_MiThermometer#93]
if i try to connect a xiaomi LYWSD03MMC with a smartphone - android 10- the connection is established without requiring the pin; i can change the config too. pin has been changed using the flasher, firmware v2.9...

is it normal behaviour or a bug?!

(on my pc -windows 10- i have no problems and the pin is required as expected)

thanks

**Comment by pvvx** [comment]
Ver 3.1 - Fix security attributes for pin-code...

**Comment by 50494554524F** [comment]
perfect!
