### ISSUE TITLE
No Bluetooth signal LYWSD03MMC 

### ISSUE THREAD

**Issue by pettergreenwood** [pvvx/ATC_MiThermometer#95]
Hi.

Every things worked well during the update to FW Custom Firmware Version 3.1.
The temp start sending out the new BT name and looked great.
When after approx. 2 days I started to take a look at the Raspberry pi where I wanted to pick up the data I noticed that I couldn't start the bluetoothctl# "scan on" I got this error: org.bluez.Error.NotReady the same issue with power on etc.
Restarted the Rpi and started the troubleshoot but couldn't find the issue. I then removed the battery and I could start scanning on BT again. I then connected the battery again and noticed the LYWSD03MMC had stopped sending out BT signal.
I tried to get it to work again but sadly not.

Any ideas what went wrong and any suggestions how to get it working again?

/Petter

**Comment by pvvx** [comment]
These are bluetoothctl and RPi problems.
In new versions of Bluez and on a normal USB-BT adapter, everything works correctly.
