### ISSUE TITLE
show only external data

### ISSUE THREAD

**Issue by bonuzzz** [pvvx/ATC_MiThermometer#96]
I use sketch to show external data (from mqtt in my case) on lcd, but thermometer has two cycles: 1. it shows my data / 2. it shows data from internal sensor.
Is it possible to disable showing internal data and use the thermometer only like a display?

**Comment by pvvx** [comment]
[Primary Service UUID 0x1F10, Characteristic UUID 0x1F1F, command 0x60.](https://github.com/pvvx/ATC_MiThermometer#primary-service-uuid-0x1f10-characteristic-uuid-0x1f1f)

**Xiaomi LYWSD03MMC LCD:**
Packet: 
Set buffer bits LCD: 0x60, RAW_data_LCD[1..6] -> 0x60, RAW_data_LCD[6]
Get buffer bits LCD: 0x60 -> 0x60, RAW_data_LCD[6]

Sample LYWSD03MMC show clock: 
https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html#L1227

Bitmap buffer LYWSD03MMC LCD:
https://github.com/pvvx/ATC_MiThermometer/tree/master/BoardPinout  -> Mi_LCD_Segments.jpeg

**Comment by bonuzzz** [comment]
when I write info to lcd buffer, ext.data stop working. Is it ok?

**Comment by pvvx** [comment]
Close Connect -> Restore show LCD.

[UUID первичной службы 0x1F10, характерный UUID 0x1F1F, команда 0x61.](https://github.com/pvvx/ATC_MiThermometer#primary-service-uuid-0x1f10-characteristic-uuid-0x1f1f)
[Restore show LCD: 0x61, 0x00](https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html#L1256)

**Comment by ndrwrbgs** [comment]
For posterity, the links above at the time when they were posted (default links floated to `master` and changed code locations):

> Sample LYWSD03MMC show clock:
> ~https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html#L1227~
> 🆕https://github.com/pvvx/pvvx.github.io/blob/d32d6932f59db35befec98cda0004ba18fa0d549/ATC_MiThermometer/TelinkMiFlasher.html#L1227



> [~Restore show LCD: 0x61, 0x00~](https://github.com/pvvx/pvvx.github.io/blob/master/ATC_MiThermometer/TelinkMiFlasher.html#L1256)
> 🆕https://github.com/pvvx/pvvx.github.io/blob/d32d6932f59db35befec98cda0004ba18fa0d549/ATC_MiThermometer/TelinkMiFlasher.html#L1256

So to set a 0 in the middle digit...
 1. consult the diagram from [BoardPinout](https://github.com/pvvx/ATC_MiThermometer/tree/33008241a5c58b0314d7df37ea966e1d4d6fdd32/BoardPinout), the middle digit. These are "(byte number, bit number)", note that the byte numbers change across the top 3 digits, but the bit numbers do not (this is what is happening with `lcd_digcode` in `lcd_clock`).
 2. The bits needed in byte 4, for a 0, are `0, 2, 4, 5, 6, 7`. 0 (top of right side), 2 (bottom of right side), 4 (top), 5 (top of left side), 6 (bottom of left side), 7 (bottom). This is 11110101. (bits 1 and 3 are 0)
 3. Prepare your data. 0x60 (the command) in bit 0. "Data" starts after this, so "byte 4" will be sent in the payload at index 5. E.g. `lcd_binary[0] = 0x60; lcd_binary[5] = 0b11110101;`
 4. Service UUID (from readme) 0x1F10 characteristic UUID: 0x1F1F
 5. Send that data
 6. Note: on disconnect, the LCD is restored. 0x61, 0x00 can also restore it on demand while connected
